apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: instantiate-carrier-allchannel-newproduct2
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: instantiate-carrier-allchannel-newproduct2
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: sunsu
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.suneelbaf.svc.cluster.local:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.walmart-net.suneel.pvt.wmtbaf.info:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.0.0
      name: newproduct
      version: 2
      instantiationarguments: ''
      endorsementpolicies:  ''
    channel:
      name: allchannel