apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: join-allchannel-carrier-peer1
  namespace: carrier-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: join-allchannel-carrier-peer1
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: gorilla
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer1
      address: peer1.carrier-net.svc.cluster.local:7061
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.suneelbaf.svc.cluster.local:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer3.supplychain-net.svc.cluster.local:7050

