apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIKxBNYehnpiZIrN+9EslqyxztAWUQ2pkHFietUjM/vAOEp9TCpxTCplTCngKWggBEAEaBgjG
      gvX8BSIKc3lzY2hhbm5lbCpAOWNjZTBjZmEzYjU2YzFmYWZjMWI2ZTA2ZWViNDA2MjNjOWVlNGVh
      YjgwYjllZmMwYzIxNzg0ZmE5MzIwNzJhYhIaEhhl5PAgJJxrT5nhShFJiMKmGAvgB5j4nlQSnFIK
      mVISllISwSsKB09yZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVDViOGJaQTFjSzhzVWNXd2g0VkpUT3J2UlBRd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TURNeE1UQXhOakk0V2hjTk1qTXdPREl4TVRBeE5qSTRX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJFbUNl
      VnNWcVhuMjJUWDZvWDN2K2tMZFZhZmk2eWw0QW42VEx3dC83R0ZBZzVua0tETzkKSGE1T2ZTVFBh
      Z01aendMMVJScWZuK3IrREYrREdCbFI3NEdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU1hRTmtIcnJuTGZUWmtVeHVSQ1lpd2E0
      VXNlakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXBkblljSEFwUzVUYWpuMFZaSlMrYU0xbDd3
      MVJlNmNUTjdRdUovQWwKdnBVQ0lFUTIxSGIwMTdmU1AxSGxWbWJJR3d3SzRpTHIyMEVFNHM2NzRn
      ZXpoZ0k2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM1RENDQW9xZ0F3SUJBZ0lVTDJTaU01NlZqbXI2R256NlpITUk2RS8va2FFd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TURNeE1UQXlNakF3V2hjTk1q
      RXhNRE14TVRBeU56QXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3
      WmpiR2xsYm5ReEhqQWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhXWklqUnl3VGVBUDhsOUJiYnhrbXdFMzlL
      SGwrL20KSnNQRlNFWlFFUHloQWFZd3BZT3JVRzVKZCtld2RaNlBvQXBHNzg1ZHVnVjVuODRnR3FY
      dkVKdWpnZ0VWTUlJQgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVWk1UFN4U3FyCmZMNGl3c2s1Uzd5M080RitJM293SHdZRFZSMGpCQmd3Rm9B
      VWwwRFpCNjY1eTMwMlpGTWJrUW1Jc0d1RkxIb3cKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhN
      dE5qbGtOemc0TldZNE5pMTRPRFZ3WkRDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25z
      aVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1s
      c2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFE
      QWdOSQpBREJGQWlFQTNhOU0zTXNER2tlQm9YYUZ1M1VZZXYvb2NPQS9sVVNIalhCR2JkT0pwOEFD
      SUdiZ1Q3TWVRQ1NxCkpvUFB2TDBRUXJTTFdtNUE5cW5Lc1ZkdWtSKzNscDlmCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVQ1YjhiWkExY0s4c1VjV3doNFZKVE9ydlJQUXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1ETXhNVEF4TmpJNFdoY05Nak13
      T0RJeE1UQXhOakk0V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCRW1DZVZzVnFYbjIyVFg2b1gzditrTGRWYWZpNnlsNEFuNlRMd3QvN0dGQWc1bmtL
      RE85CkhhNU9mU1RQYWdNWnp3TDFSUnFmbityK0RGK0RHQmxSNzRHalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNYUU5rSHJybkxm
      VFprVXh1UkNZaXdhNFVzZWpBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUFwZG5ZY0hBcFM1VGFq
      bjBWWkpTK2FNMWw3dzFSZTZjVE43UXVKL0FsCnZwVUNJRVEyMUhiMDE3ZlNQMUhsVm1iSUd3d0s0
      aUxyMjBFRTRzNjc0Z2V6aGdJNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxq0EgoNQ29uc2Vuc3VzVHlwZRKi
      EhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBseWNoYWluLW5ldC5zdmMuY2x1c3Rl
      ci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lC
      QWdJVURiRmp6dUFUeUVJN05uR1JvemFiTncrMDhXTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRdwpIaGNOTWpBeE1ETXhNVEF5TXpBd1doY05NakV4TURNeE1UQXlPREF3V2pCdU1Rc3dD
      UVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZj
      bVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQ0FBUWhQZlJ4R3E0QXdyU05oWDhEUlFqNzA1M01zYUxmCitVMmpoT05uNncrZTVQQ2Ru
      YkM0Vy8rS2tQc3lyU0lJbXNOQ1hjQ25JSlpKUkFhcmlIYVdRZzZabzRJQlBUQ0MKQVRrd0RnWURW
      UjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApB
      akFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUjUwb2k5Nk1YNnhxV1BOZmtPcFFSOW9x
      TGJyakFmCkJnTlZIU01FR0RBV2dCU1hRTmtIcnJuTGZUWmtVeHVSQ1lpd2E0VXNlakJQQmdOVkhS
      RUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxu
      TjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJn
      Y0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVBYwpJYlBWMlcvM1RZ
      YTBOaTZPSmxGa3ZQdFRockp6amtYVVB6UE80Y2R0QWlBYXIwbHQwQW55K0pmSGViSnRjMWwxCm1p
      Mk9iVEw0aTkzTkFhdXZ0K1hTUHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLfCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVURiRmp6dUFUeUVJN05u
      R1JvemFiTncrMDhXTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1E
      TXhNVEF5TXpBd1doY05NakV4TURNeE1UQXlPREF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWhQZlJ4R3E0
      QXdyU05oWDhEUlFqNzA1M01zYUxmCitVMmpoT05uNncrZTVQQ2RuYkM0Vy8rS2tQc3lyU0lJbXNO
      Q1hjQ25JSlpKUkFhcmlIYVdRZzZabzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCUjUwb2k5Nk1YNnhxV1BOZmtPcFFSOW9xTGJyakFmCkJnTlZIU01FR0RB
      V2dCU1hRTmtIcnJuTGZUWmtVeHVSQ1lpd2E0VXNlakJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21W
      eU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVs
      ZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2
      ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5
      WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5
      TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUVBYwpJYlBWMlcvM1RZYTBOaTZPSmxGa3ZQdFRockp6
      amtYVVB6UE80Y2R0QWlBYXIwbHQwQW55K0pmSGViSnRjMWwxCm1pMk9iVEw0aTkzTkFhdXZ0K1hT
      UHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1p
      bnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9u
      EhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFk
      bWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEvojCgtDb25z
      b3J0aXVtcxLqIxKfIwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEoUjEqciCgpjYXJyaWVyTVNQEpgi
      GrQgCgNNU1ASrCASoSASniAKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVFQWpNbGt1ZkpwV0o5cUtlSmQ2REVTcytZRzR3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFd016RXhNREUzTURSYUZ3MHlNekE0TWpFeE1E
      RTNNRFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRT2l1
      VnExdk4xY0l2dUs4Mkx2cXFJYUltT281RFBFZ3FtVkprQmkvd3pmUTdpWFZHTmR0NFhNRjExRk13
      dwpUUUJYQUhmNFFKN0dpcWpIMndmQjliYUZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWFaaWlKOTBXaTBZL0NxZGljNVJOM3kw
      bmVVd3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUw2am1HQ3pUemZ4bExydC9uTC92eVlaU0Yr
      a3JrT3lxdDVnYk14NHdrVlVBaUFBLzlaVgo4SDY1cVNKL0hYc1RZQ0Jad1hGc3ZQM2JxaDh1dy8r
      eU9taXlGUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM4RENDQXBhZ0F3SUJBZ0lVR2l3blcvOE90RGE5djkxaTZpUXAzYnpNYnZj
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1ERXdNekV4TURJMU1EQmFGdzB5TVRF
      d016RXhNRE13TURCYU1Ia3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIekFOQmdOVgpCQXNUQm1O
      c2FXVnVkREFPQmdOVkJBc1RCMk5oY25KcFpYSXhHakFZQmdOVkJBTU1FVUZrYldsdVFHTmhjbkpw
      ClpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFbjFNUzFPMlRPb2V6
      c1VtK3J1emkKL3RZMVkweDhTMU1uZ0lXNmpzenNLeHNDcWZaS3hlZVFjYUFKYzduUm5jYXQvU0lO
      cEtNS0JXZnRZVXZPMCsxSgpuYU9DQVJrd2dnRVZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXCkJCUmt2bHNzcHkwcDBWa0VaQkJDb3lJeXFWT2VFekFm
      QmdOVkhTTUVHREFXZ0JScG1LSW4zUmFMUmo4S3AySnoKbEUzZkxTZDVUREFrQmdOVkhSRUVIVEFi
      Z2hsallTMTBiMjlzY3kwMk9XUTNPRGcxWmpnMkxYRjZiVFJyTUlHTwpCZ2dxQXdRRkJnY0lBUVNC
      Z1hzaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1Cklqb2lkSEox
      WlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVkyRnljbWxsY2lJc0ltaG1Ma1Z1Y205c2JHMWwK
      Ym5SSlJDSTZJa0ZrYldsdVFHTmhjbkpwWlhJdGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVk
      Q0o5ZlRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUErUlhoL1JHc1k1OXJHeTdoa25kbGJ0dHlw
      NWxjeVJTdnhqU1hyVGl1CjJFb0NJREVBL3J5RGdrckRlRkkxRnRSZktkbEJnOEVIejRrT0o1dUl3
      TGlLRE5FSAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVFQWpNbGt1ZkpwV0o5
      cUtlSmQ2REVTcytZRzR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFd016RXhN
      REUzTURSYUZ3MHlNekE0TWpFeE1ERTNNRFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFRT2l1VnExdk4xY0l2dUs4Mkx2cXFJYUltT281RFBFZ3FtVkprQmkv
      d3pmUTdpWFZHTmR0NFhNRjExRk13dwpUUUJYQUhmNFFKN0dpcWpIMndmQjliYUZvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWFa
      aWlKOTBXaTBZL0NxZGljNVJOM3kwbmVVd3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUw2am1H
      Q3pUemZ4bExydC9uTC92eVlaU0Yra3JrT3lxdDVnYk14NHdrVlVBaUFBLzlaVgo4SDY1cVNKL0hY
      c1RZQ0Jad1hGc3ZQM2JxaDh1dy8reU9taXlGUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Wu4LCAES9AUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFn
      SVVFQWpNbGt1ZkpwV0o5cUtlSmQ2REVTcytZRzR3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERB
      ZUZ3MHkKTURFd016RXhNREUzTURSYUZ3MHlNekE0TWpFeE1ERTNNRFJhTUZveEN6QUpCZ05WQkFZ
      VEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0
      R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRT2l1VnExdk4xY0l2dUs4Mkx2cXFJYUlt
      T281RFBFZ3FtVkprQmkvd3pmUTdpWFZHTmR0NFhNRjExRk13dwpUUUJYQUhmNFFKN0dpcWpIMndm
      QjliYUZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpB
      ZEJnTlZIUTRFRmdRVWFaaWlKOTBXaTBZL0NxZGljNVJOM3kwbmVVd3dDZ1lJS29aSXpqMEUKQXdJ
      RFNBQXdSUUloQUw2am1HQ3pUemZ4bExydC9uTC92eVlaU0Yra3JrT3lxdDVnYk14NHdrVlVBaUFB
      LzlaVgo4SDY1cVNKL0hYc1RZQ0Jad1hGc3ZQM2JxaDh1dy8reU9taXlGUT09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KEgZjbGllbnQa8gUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQitEQ0NBWjZnQXdJQkFnSVVFQWpNbGt1ZkpwV0o5cUtlSmQ2REVTcytZRzR3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFd016RXhNREUzTURSYUZ3MHlNekE0TWpFeE1ERTNN
      RFJhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZC
      QWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZ
      MkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRT2l1VnEx
      dk4xY0l2dUs4Mkx2cXFJYUltT281RFBFZ3FtVkprQmkvd3pmUTdpWFZHTmR0NFhNRjExRk13dwpU
      UUJYQUhmNFFKN0dpcWpIMndmQjliYUZvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWFaaWlKOTBXaTBZL0NxZGljNVJOM3kwbmVV
      d3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQUw2am1HQ3pUemZ4bExydC9uTC92eVlaU0Yra3Jr
      T3lxdDVnYk14NHdrVlVBaUFBLzlaVgo4SDY1cVNKL0hYc1RZQ0Jad1hGc3ZQM2JxaDh1dy8reU9t
      aXlGUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGmAKEE9yZGVyZXJBZGRyZXNzZXMS
      TBIxCi9vcmRlcmVyMy5zdXBwbHljaGFpbi1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODQ0MxoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRt
      aW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFI
      YXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRl
      cnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
