apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: gorilla
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIH2ZA6uKDmYKU5mBr+JQURtP6DENc0AlWrXZ0wpXcS9PEp9TCpxTCplTCngKWggBEAEaBgiA
      j5b9BSIKc3lzY2hhbm5lbCpAYzA5MzE4YjRiZmJkN2RjNjVmYmUzMTcyNDAzOTk5YmNkZmU2NzEy
      MmE4NDg2NDQyNzNjOGJmNjBlMGZmYzJkMhIaEhjK6a3JEwaJnqQR3k6W2fQlASZu4rlHKcgSnFIK
      mVISllISwSsKB09yZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVVEc1Nyt1dnd3Q0RsUUdXYjd5aC9oMFQ3dFkwd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBMk1UY3hOelV6V2hjTk1qTXdPREkzTVRjeE56VXpX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDMXJP
      bFI3NDF5a0NWcURHeVRVS1hQaXFKRGNCYkYrcWlXOVprSDc3QWJxaFBWako1bWkKVUxrS3FGQ3lP
      aU1EZ1NZRkp5YUdKd25JeDFrUzdiYjVMRVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUWZMK1hnckJBM1U1ZWd4QlAzbDdYelZ3
      b2JHakFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTIvcTJaWGxKL21VajF6SjlsUEk3M2MrWkw4
      Nkd4NDM0SXJKamFlZVMKNnd3Q0lHcmhUMDFhcThyQ1JsUXdiSVR5WGpINkhJdy91cG9HR3hxUVlo
      azFvK0IyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0ekNDQW9xZ0F3SUJBZ0lVV1h0a2YvcTFoVm1lUElISW1PWUdUaG1XV3JBd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBMk1UY3lNakF3V2hjTk1q
      RXhNVEEyTVRjeU56QXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3
      WmpiR2xsYm5ReEhqQWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxnSFROOEliWkJMNmVvRS9TRFpEelpnRVl6
      YjdmMTIKSk1vaWlUaEhZUFBkSmhqc0J6SUlXcEM1V2UwSmZVSnUxaWc1dERXeHR4cUMwU0pGT0p2
      TWVKYWpnZ0VWTUlJQgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVTBqQ0ZraEFjCmIwQXBSN29wcXc4K1dVeUxJYWd3SHdZRFZSMGpCQmd3Rm9B
      VUh5L2w0S3dRTjFPWG9NUVQ5NWUxODFjS0d4b3cKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhN
      dE5qbGtOemc0TldZNE5pMXVkelJyT1RDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25z
      aVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1s
      c2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFE
      QWdOSApBREJFQWlCUlNERWVoWThkZVFuYjhieEp1VG5xcUcwVUlRMFdGRWs1dVlpaVRoaktFQUln
      RmhiQUdKRWFZejh4Cit0UHdGdk5jVTVTVDJueldna0NOc1ZRZThQQkRha1k9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVVRHNTcrdXZ3d0NEbFFHV2I3eWgvaDBUN3RZMHdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQTJNVGN4TnpVeldoY05Nak13
      T0RJM01UY3hOelV6V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCQzFyT2xSNzQxeWtDVnFER3lUVUtYUGlxSkRjQmJGK3FpVzlaa0g3N0FicWhQVmpK
      NW1pClVMa0txRkN5T2lNRGdTWUZKeWFHSnduSXgxa1M3YmI1TEVTalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlFmTCtYZ3JCQTNV
      NWVneEJQM2w3WHpWd29iR2pBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUEyL3EyWlhsSi9tVWox
      eko5bFBJNzNjK1pMODZHeDQzNElySmphZWVTCjZ3d0NJR3JoVDAxYXE4ckNSbFF3YklUeVhqSDZI
      SXcvdXBvR0d4cVFZaGsxbytCMgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxq0EgoNQ29uc2Vuc3VzVHlwZRKi
      EhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBseWNoYWluLW5ldC5zdmMuY2x1c3Rl
      ci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lC
      QWdJVVJYSkg4MldaODBSSHZYRkRLcjhVMVhRQlFqTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRdwpIaGNOTWpBeE1UQTJNVGN5TWpBd1doY05NakV4TVRBMk1UY3lOekF3V2pCdU1Rc3dD
      UVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZj
      bVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQ0FBUWdGT2Y4S2VFZ2lBamJrUm8vVXc0c2IwbXBIWDZhCnE0RWdRQlY3QVZ1N2p4ZGlj
      bGYyN21jdzQxaVhKenRNV21QcEYwNG9rUjdYbE9Tc3NORlNYT3lhbzRJQlBUQ0MKQVRrd0RnWURW
      UjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApB
      akFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVEwxdDlVNWlwTE1HVzMxLzJ2SVVKb21z
      WGFDVEFmCkJnTlZIU01FR0RBV2dCUWZMK1hnckJBM1U1ZWd4QlAzbDdYelZ3b2JHakJQQmdOVkhS
      RUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxu
      TjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJn
      Y0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUUyeQpZRGNvWVhaWTZZ
      YVJ2eU1TSGdJR0h1VG1RcEV3VDVBT3lJSzh5THdRQWlCZFp6Q05kZnpyaURlempUUTVwcEJ3CjZp
      T3lmMll1MW16aXBDZjVjUVQ3K3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLfCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVVJYSkg4MldaODBSSHZY
      RkRLcjhVMVhRQlFqTXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1U
      QTJNVGN5TWpBd1doY05NakV4TVRBMk1UY3lOekF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUWdGT2Y4S2VF
      Z2lBamJrUm8vVXc0c2IwbXBIWDZhCnE0RWdRQlY3QVZ1N2p4ZGljbGYyN21jdzQxaVhKenRNV21Q
      cEYwNG9rUjdYbE9Tc3NORlNYT3lhbzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVEwxdDlVNWlwTE1HVzMxLzJ2SVVKb21zWGFDVEFmCkJnTlZIU01FR0RB
      V2dCUWZMK1hnckJBM1U1ZWd4QlAzbDdYelZ3b2JHakJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21W
      eU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVs
      ZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2
      ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5
      WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5
      TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUUyeQpZRGNvWVhaWTZZYVJ2eU1TSGdJR0h1VG1RcEV3
      VDVBT3lJSzh5THdRQWlCZFp6Q05kZnpyaURlempUUTVwcEJ3CjZpT3lmMll1MW16aXBDZjVjUVQ3
      K3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1p
      bnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9u
      EhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFk
      bWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEvojCgtDb25z
      b3J0aXVtcxLqIxKfIwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEoUjEqciCgpjYXJyaWVyTVNQEpgi
      GrQgCgNNU1ASrCASoSASniAKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVkdEh0bWdNc0tRQmtNNHA5TTYxU1VoSHFDd2d3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EWXhOekU0TUROYUZ3MHlNekE0TWpjeE56
      RTRNRE5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTcy9F
      TzRBbWV3QjM3MFB2MThRZEtzUVNkRGpQWExTWUN5Y2srVFZrRi9PZTNDdVRMcFlFN0pubUU5TEFn
      RwpBZXBkcmdpSU9DeStGczNkYTUzUGhCemRvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXlZd21hRk5LWXhjTmp3VFFseTVpd0pM
      WEtFTXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUkyN0UzTE5ZaStjNllvNFlkWjk1RU9QaHBy
      UVpNSzQvamFJRXZ3VFdHaDhBaUVBcHBGZQp0SitQMjgyZWt1b3NJY0VrNnZFR1dkYng4N0Z6NGha
      OXlvVjlnNVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM3ekNDQXBhZ0F3SUJBZ0lVWncyMUZTSEtYd0Q0M0VXS3dldkZKT3E1Vk0w
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1ERXhNRFl4TnpJeU1EQmFGdzB5TVRF
      eE1EWXhOekkzTURCYU1Ia3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIekFOQmdOVgpCQXNUQm1O
      c2FXVnVkREFPQmdOVkJBc1RCMk5oY25KcFpYSXhHakFZQmdOVkJBTU1FVUZrYldsdVFHTmhjbkpw
      ClpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFajB4ZzdGSXVJQ2cr
      QUxMQjF5Wm8KbzZDYWx5TkhQdVB1K09tUE4raXJXbWhDME9iTVdDVG91enNwMTE5RWFKc094TzZZ
      SlppN0MrbXY2T2c5MHJhVQp0cU9DQVJrd2dnRVZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXCkJCU3JVLyt0M0NrZFdBZXc4ZkFXSC9Vb0t3TU43VEFm
      QmdOVkhTTUVHREFXZ0JUSmpDWm9VMHBqRncyUEJOQ1gKTG1MQWt0Y29RekFrQmdOVkhSRUVIVEFi
      Z2hsallTMTBiMjlzY3kwMk9XUTNPRGcxWmpnMkxYTnFhM2htTUlHTwpCZ2dxQXdRRkJnY0lBUVNC
      Z1hzaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1Cklqb2lkSEox
      WlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVkyRnljbWxsY2lJc0ltaG1Ma1Z1Y205c2JHMWwK
      Ym5SSlJDSTZJa0ZrYldsdVFHTmhjbkpwWlhJdGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVk
      Q0o5ZlRBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQWdKYkZQazMyT2V2MnVldEFiV2duUThHV3pr
      VjI4V0s2R2dUL2NyTzV5Cm1RSWdlMHFDUU51bjVINzdhME1wejM5UmZDVFNvUzRZNU1qS1c5VjJI
      SVgzL0JvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVkdEh0bWdNc0tRQmtN
      NHA5TTYxU1VoSHFDd2d3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EWXhO
      ekU0TUROYUZ3MHlNekE0TWpjeE56RTRNRE5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFTcy9FTzRBbWV3QjM3MFB2MThRZEtzUVNkRGpQWExTWUN5Y2srVFZr
      Ri9PZTNDdVRMcFlFN0pubUU5TEFnRwpBZXBkcmdpSU9DeStGczNkYTUzUGhCemRvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXlZ
      d21hRk5LWXhjTmp3VFFseTVpd0pMWEtFTXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUkyN0Uz
      TE5ZaStjNllvNFlkWjk1RU9QaHByUVpNSzQvamFJRXZ3VFdHaDhBaUVBcHBGZQp0SitQMjgyZWt1
      b3NJY0VrNnZFR1dkYng4N0Z6NGhaOXlvVjlnNVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Wu4LCAES9AUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFn
      SVVkdEh0bWdNc0tRQmtNNHA5TTYxU1VoSHFDd2d3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERB
      ZUZ3MHkKTURFeE1EWXhOekU0TUROYUZ3MHlNekE0TWpjeE56RTRNRE5hTUZveEN6QUpCZ05WQkFZ
      VEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0
      R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTcy9FTzRBbWV3QjM3MFB2MThRZEtzUVNk
      RGpQWExTWUN5Y2srVFZrRi9PZTNDdVRMcFlFN0pubUU5TEFnRwpBZXBkcmdpSU9DeStGczNkYTUz
      UGhCemRvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpB
      ZEJnTlZIUTRFRmdRVXlZd21hRk5LWXhjTmp3VFFseTVpd0pMWEtFTXdDZ1lJS29aSXpqMEUKQXdJ
      RFNRQXdSZ0loQUkyN0UzTE5ZaStjNllvNFlkWjk1RU9QaHByUVpNSzQvamFJRXZ3VFdHaDhBaUVB
      cHBGZQp0SitQMjgyZWt1b3NJY0VrNnZFR1dkYng4N0Z6NGhaOXlvVjlnNVk9Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KEgZjbGllbnQa8gUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQitUQ0NBWjZnQXdJQkFnSVVkdEh0bWdNc0tRQmtNNHA5TTYxU1VoSHFDd2d3Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EWXhOekU0TUROYUZ3MHlNekE0TWpjeE56RTRN
      RE5hTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZC
      QWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZ
      MkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTcy9FTzRB
      bWV3QjM3MFB2MThRZEtzUVNkRGpQWExTWUN5Y2srVFZrRi9PZTNDdVRMcFlFN0pubUU5TEFnRwpB
      ZXBkcmdpSU9DeStGczNkYTUzUGhCemRvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVXlZd21hRk5LWXhjTmp3VFFseTVpd0pMWEtF
      TXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQUkyN0UzTE5ZaStjNllvNFlkWjk1RU9QaHByUVpN
      SzQvamFJRXZ3VFdHaDhBaUVBcHBGZQp0SitQMjgyZWt1b3NJY0VrNnZFR1dkYng4N0Z6NGhaOXlv
      VjlnNVk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGmAKEE9yZGVyZXJBZGRyZXNzZXMS
      TBIxCi9vcmRlcmVyMy5zdXBwbHljaGFpbi1uZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODQ0MxoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRt
      aW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFI
      YXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1p
      bnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
