apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIO8sqg3WHW7AQy+rDzGy/r8YTZMYj9FeC66Lne7lY8kDEp9TCpxTCplTCngKWggBEAEaBgiu
      zon9BSIKc3lzY2hhbm5lbCpAZDU2NjdiYmM5NjhkOGM3YzNhMzBjM2Y0ZDViNTBmZjg0YmQ1NmFm
      MTM1YWRiNWYyZWEzNDJlNDY4YjU0MGU2MxIaEhhFhUGSoVIhXsIlT76Wusf59AZRRMjDVT4SnFIK
      mVISllISwSsKB09yZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvekND
      QWFhZ0F3SUJBZ0lVRDhIamtnVkFMRWxqRWNhS0k5UDEyRzFnWk1Rd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBME1EZ3lNekEzV2hjTk1qTXdPREkxTURneU16QTNX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJeFd5
      ZHhpVms1Vi9RbDlLNHR3N3o5N3U0K3lVRzF1MGlLWSt5MzA3Y2ZyZWI1aldNQ2MKdWVRTXVMSDY5
      MStIVzRKRGhudHlFNUk1T0NaVHdYNEh4SXlqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUktkblRFOE1uQW4wckUwTGZlOFJORG5o
      TUxDakFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlBT3pCRDZYQmU2TjVZR3AxTStvcTdQZ1JDK3dZ
      ZU55aGU3bDFKNWdJMG8KM0FJZ0Rtd0cxOEk3ajFqaXpTZDRuL0o4WlVTTjhWN1UyQmhlOU1oeVZH
      U25oK0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM1RENDQW9xZ0F3SUJBZ0lVYWhwMmJCRm5RNis0TE94QXhqOWlYK0VRa1hVd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBME1EZ3lOekF3V2hjTk1q
      RXhNVEEwTURnek1qQXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3
      WmpiR2xsYm5ReEhqQWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkFGaUVmeUx5cnFxaWY2cWxmaENDVHk1RkRJ
      MGVGOVcKZHdpc0U2dHlJUDJYLythT3dHZElsblhqRlVIMVdGUDdXS0V5ZUF5Um5kVmQrTEg2TTdt
      clZ2R2pnZ0VWTUlJQgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVW9VNVE1cXZ6Cm1VSmprM0RQa2xPN3V3Zk5HazB3SHdZRFZSMGpCQmd3Rm9B
      VVNuWjB4UERKd0o5S3hOQzMzdkVUUTU0VEN3b3cKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhN
      dE5qbGtOemc0TldZNE5pMXpZbkZ1YURDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25z
      aVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1s
      c2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFE
      QWdOSQpBREJGQWlFQWhlL0tZUnRIUUtuYzJ6VTRiQ1VTT0t4R2VhSVJQMk1rVjgvOW12Um9URU1D
      SUgxZWF0QjZhWWU1Clh0MmZNTnlpU1BxYWdpYWVnTFd6RHQyQmR0S3NZb3lDCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlCL3pDQ0FhYWdBd0lCQWdJVUQ4SGprZ1ZBTEVsakVjYUtJOVAxMkcxZ1pNUXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQTBNRGd5TXpBM1doY05Nak13
      T0RJMU1EZ3lNekEzV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSXhXeWR4aVZrNVYvUWw5SzR0dzd6OTd1NCt5VUcxdTBpS1kreTMwN2NmcmViNWpX
      TUNjCnVlUU11TEg2OTErSFc0SkRobnR5RTVJNU9DWlR3WDRIeEl5alFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlJLZG5URThNbkFu
      MHJFMExmZThSTkRuaE1MQ2pBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQU96QkQ2WEJlNk41WUdw
      MU0rb3E3UGdSQyt3WWVOeWhlN2wxSjVnSTBvCjNBSWdEbXdHMThJN2oxaml6U2Q0bi9KOFpVU044
      VjdVMkJoZTlNaHlWR1NuaCtJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjcK
      B1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjcK
      B1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1TUBoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxq0EgoNQ29uc2Vuc3VzVHlwZRKi
      EhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBseWNoYWluLW5ldC5zdmMuY2x1c3Rl
      ci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lC
      QWdJVUxnUWY3T1ROVTY1TGZheGJxcUllTG9NLzlQc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRdwpIaGNOTWpBeE1UQTBNRGd5TnpBd1doY05NakV4TVRBME1EZ3pNakF3V2pCdU1Rc3dD
      UVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZj
      bVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQ0FBUUpBWUVZWlVlVU1LUU1xTUZodU9Tb0pBa0xuTDU0Ck5hZWlNUmJkc0I1LzA0NzJz
      OWRzRmVoc29tWXQxdVpReVIwNlRuNG15RGJ0YzZaOFFKL2xsZ1lSbzRJQlBUQ0MKQVRrd0RnWURW
      UjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApB
      akFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCU1k1SlM3dC95NFRIckIzb3N0SlFrTENk
      M0hkVEFmCkJnTlZIU01FR0RBV2dCUktkblRFOE1uQW4wckUwTGZlOFJORG5oTUxDakJQQmdOVkhS
      RUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxu
      TjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJn
      Y0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURxeAp0TlpCY3ZMbjcw
      c2NFR3dXYUg5SXdEMHN0NndKZnR0K2c1amRQaWFRQWlBRzJUeUgxcldUcEtWQkJ6UDRraWdsClZp
      dnlSTWQ0VXdaaXpiMDlsaXYzTHc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLfCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVUxnUWY3T1ROVTY1TGZh
      eGJxcUllTG9NLzlQc3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1U
      QTBNRGd5TnpBd1doY05NakV4TVRBME1EZ3pNakF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUUpBWUVZWlVl
      VU1LUU1xTUZodU9Tb0pBa0xuTDU0Ck5hZWlNUmJkc0I1LzA0NzJzOWRzRmVoc29tWXQxdVpReVIw
      NlRuNG15RGJ0YzZaOFFKL2xsZ1lSbzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCU1k1SlM3dC95NFRIckIzb3N0SlFrTENkM0hkVEFmCkJnTlZIU01FR0RB
      V2dCUktkblRFOE1uQW4wckUwTGZlOFJORG5oTUxDakJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21W
      eU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVs
      ZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2
      ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5
      WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5
      TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURxeAp0TlpCY3ZMbjcwc2NFR3dXYUg5SXdEMHN0NndK
      ZnR0K2c1amRQaWFRQWlBRzJUeUgxcldUcEtWQkJ6UDRraWdsClZpdnlSTWQ0VXdaaXpiMDlsaXYz
      THc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1p
      bnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoK
      BkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zEvojCgtDb25z
      b3J0aXVtcxLqIxKfIwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEoUjEqciCgpjYXJyaWVyTVNQEpgi
      GrQgCgNNU1ASrCASoSASniAKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVQWlA3aHFtS2cvV0lGY2VhRWRpd1FPSjhOcm93Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EUXdPREl6TVRaYUZ3MHlNekE0TWpVd09E
      SXpNVFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRWVhL
      OEVKU1EzREJOOWxNb0J1ZjJTRXQrTnl6U1dCVmVMZnJvV2EvSURaaHFuT2dHb3ZVbjVKU2dpRWtF
      TwplSEJ6czVXcFRaNmxSQXNwRVUyR3FuOUNvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVU5UTmdzTGtxZXRORWd4M2xxcm9uOFVT
      d1l6WXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQU1xZDV4eVpSTndKU2ZkYlpQSGRDYk9wTFNT
      a2h1SzYxZzhHVU9Xc2ludFFBaUVBeGhveApPMEc4am0vcDE0ak5ldGVSOThuSkR4MEZNUHZhMUd3
      cnd4ci9ERG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM4RENDQXBhZ0F3SUJBZ0lVRkV3bjZKSll4VlRtY3NOT1RxZmJBTzJTam5n
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1ERXhNRFF3T0RJM01EQmFGdzB5TVRF
      eE1EUXdPRE15TURCYU1Ia3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIekFOQmdOVgpCQXNUQm1O
      c2FXVnVkREFPQmdOVkJBc1RCMk5oY25KcFpYSXhHakFZQmdOVkJBTU1FVUZrYldsdVFHTmhjbkpw
      ClpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFd1VJVHM0blkwMnJr
      SHBHcW9vUjQKd1VEWDZEVmhXRnl3WnFOWFpBdFN2Vjd4MzJib0U4YzA3UTdFSWtqdHNZbWZLc3pU
      NjI1OGV5M0E1UzJYa2xWOQp1cU9DQVJrd2dnRVZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXCkJCUm1maHNnbkM2cms1eTJWS0hLdzBXSldzbWxCVEFm
      QmdOVkhTTUVHREFXZ0JRMU0yQ3d1U3A2MDBTREhlV3EKdWlmeFJMQmpOakFrQmdOVkhSRUVIVEFi
      Z2hsallTMTBiMjlzY3kwMk9XUTNPRGcxWmpnMkxYRmpiWFptTUlHTwpCZ2dxQXdRRkJnY0lBUVNC
      Z1hzaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1Cklqb2lkSEox
      WlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVkyRnljbWxsY2lJc0ltaG1Ma1Z1Y205c2JHMWwK
      Ym5SSlJDSTZJa0ZrYldsdVFHTmhjbkpwWlhJdGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVk
      Q0o5ZlRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUE5V2dHRFlVU2JpblRWMzNlMW44bXg1bFJE
      ME5nVVRqRXJWeWZCaUR3CnNXQUNJRjJORCtJekNLV3BvQVovclJBdjBUQUEwZm1YL2tyWG5vSVVF
      SkYyMDVrcwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFnSVVQWlA3aHFtS2cvV0lG
      Y2VhRWRpd1FPSjhOcm93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EUXdP
      REl6TVRaYUZ3MHlNekE0TWpVd09ESXpNVFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFRWVhLOEVKU1EzREJOOWxNb0J1ZjJTRXQrTnl6U1dCVmVMZnJvV2Ev
      SURaaHFuT2dHb3ZVbjVKU2dpRWtFTwplSEJ6czVXcFRaNmxSQXNwRVUyR3FuOUNvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVU5U
      TmdzTGtxZXRORWd4M2xxcm9uOFVTd1l6WXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQU1xZDV4
      eVpSTndKU2ZkYlpQSGRDYk9wTFNTa2h1SzYxZzhHVU9Xc2ludFFBaUVBeGhveApPMEc4am0vcDE0
      ak5ldGVSOThuSkR4MEZNUHZhMUd3cnd4ci9ERG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Wu4LCAES9AUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitUQ0NBWjZnQXdJQkFn
      SVVQWlA3aHFtS2cvV0lGY2VhRWRpd1FPSjhOcm93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERB
      ZUZ3MHkKTURFeE1EUXdPREl6TVRaYUZ3MHlNekE0TWpVd09ESXpNVFphTUZveEN6QUpCZ05WQkFZ
      VEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0
      R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRWVhLOEVKU1EzREJOOWxNb0J1ZjJTRXQr
      Tnl6U1dCVmVMZnJvV2EvSURaaHFuT2dHb3ZVbjVKU2dpRWtFTwplSEJ6czVXcFRaNmxSQXNwRVUy
      R3FuOUNvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpB
      ZEJnTlZIUTRFRmdRVU5UTmdzTGtxZXRORWd4M2xxcm9uOFVTd1l6WXdDZ1lJS29aSXpqMEUKQXdJ
      RFNRQXdSZ0loQU1xZDV4eVpSTndKU2ZkYlpQSGRDYk9wTFNTa2h1SzYxZzhHVU9Xc2ludFFBaUVB
      eGhveApPMEc4am0vcDE0ak5ldGVSOThuSkR4MEZNUHZhMUd3cnd4ci9ERG89Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KEgZjbGllbnQa8gUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQitUQ0NBWjZnQXdJQkFnSVVQWlA3aHFtS2cvV0lGY2VhRWRpd1FPSjhOcm93Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1EUXdPREl6TVRaYUZ3MHlNekE0TWpVd09ESXpN
      VFphTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZC
      QWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZ
      MkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFRWVhLOEVK
      U1EzREJOOWxNb0J1ZjJTRXQrTnl6U1dCVmVMZnJvV2EvSURaaHFuT2dHb3ZVbjVKU2dpRWtFTwpl
      SEJ6czVXcFRaNmxSQXNwRVUyR3FuOUNvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVU5UTmdzTGtxZXRORWd4M2xxcm9uOFVTd1l6
      WXdDZ1lJS29aSXpqMEUKQXdJRFNRQXdSZ0loQU1xZDV4eVpSTndKU2ZkYlpQSGRDYk9wTFNTa2h1
      SzYxZzhHVU9Xc2ludFFBaUVBeGhveApPMEc4am0vcDE0ak5ldGVSOThuSkR4MEZNUHZhMUd3cnd4
      ci9ERG89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiMwoHUmVhZGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdXcml0ZXJzEigS
      HggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFkbWlucxIqEiAIARIc
      EggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9yc2VtZW50EigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwK
      CgoGVjFfNF8zEgAaBkFkbWlucxomChBIYXNoaW5nQWxnb3JpdGhtEhISCAoGU0hBMjU2GgZBZG1p
      bnMaLQoZQmxvY2tEYXRhSGFzaGluZ1N0cnVjdHVyZRIQEgYI/////w8aBkFkbWlucxpgChBPcmRl
      cmVyQWRkcmVzc2VzEkwSMQovb3JkZXJlcjMuc3VwcGx5Y2hhaW4tbmV0LnN2Yy5jbHVzdGVyLmxv
      Y2FsOjg0NDMaFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIKBkFkbWlu
      cxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
