apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaILGuemU5wGt5YuIL13xrEASk9k93Dfe13be4g5F/KRGTEqdTCqRTCqFTCngKWggBEAEaBgjd
      h4T9BSIKc3lzY2hhbm5lbCpANDZkNDg3YjRlMDMxMWE3NjUwZmNjYWZmOTQwNzIyNzM1NGVlNGYw
      OWIyMGIxMjYzNzRkZDM3ODA1NmRlNGI0MRIaEhjAzuqTA6Cq/Uc30IhOperLL2WIUauyiCESpFIK
      oVISnlISySsKB09yZGVyZXISvSsS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVSllpYlhVMUVxWUpVVmZMVTVVR0tQMTdxTzlrd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EY3dOekExV2hjTk1qTXdPREkwTURjd056QTFX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJMTllW
      MjVNWlF0WkRRN3gwMzhnbUFmK2ZON0hTYU5LR2dpS2V2SEthNlNMVHBUbjVkQUMKNXg2UXJBMC92
      WEZuL2FIaU5LRWFLZGFnNG9LZ01rU2NXcXVqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU0V4ZmlsYkdsYWYvRS9YSGh1RGhxSDFG
      cWwzekFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQXFEdWxBNDA3N0U1QlVibmFwN3NhUEQzZ1pC
      S0hXMm5paENMazJBNkIKY2tBQ0lRRExBTEdhbGZuWGpJT3RpQVpLbWVaUnE5Z2drWHFYdjBlN0pD
      MkJJNkN4c3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNURDQ0FvcWdBd0lCQWdJVVZMVit5QzNEK3I0T1ZlT0dJVlVhRS93K1Nr
      b3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNRGN4TVRBd1do
      Y05NakV4TVRBek1EY3hOakF3V2pCdE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1ROHcKRFFZRFZR
      UUxFd1pqYkdsbGJuUXhIakFjQmdOVkJBTU1GVUZrYldsdVFITjFjSEJzZVdOb1lXbHVMVzVsZERC
      WgpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJIYUR4M3hQaEh5TGdLWUdZMmtMK3pL
      Mmt3cFpxb0RHCmFxcUpJOTZySjNOT2Y4ODdwSy9kQTQ4UE82VDgzWnBmMUZLZEtOYlVia1g0Y25l
      QlBReXV4QldqZ2dFVk1JSUIKRVRBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVVGZTlkbE5tYworaGFsdXJIMXk1YkN3UXo1bFRrd0h3WURWUjBqQkJn
      d0ZvQVVoTVg0cFd4cFduL3hQMXg0Ymc0YWg5UmFwZDh3CkpBWURWUjBSQkIwd0c0SVpZMkV0ZEc5
      dmJITXROamxrTnpnNE5XWTROaTAxY1dkdVlqQ0JpZ1lJS2dNRUJRWUgKQ0FFRWZuc2lZWFIwY25N
      aU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJcwpJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFjM1Z3
      CmNHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVkQ0o5ZlRBS0JnZ3Foa2pP
      UFFRREFnTkkKQURCRkFpRUE4TVUwSERaUjlQN3l3OWEvSTRPMW5pQUs3TEFhekJCalhOZ1cxblU1
      WmdZQ0lEQkF3dG5VOXlYOQozUG96UE9SWCtOUmQ2a1IzL0FqUHhuVW9xVVlHbEJIYgotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVKWWliWFUxRXFZSlVWZkxVNVVHS1AxN3FPOWt3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qQXhNVEF6TURjd056QTFXaGNO
      TWpNd09ESTBNRGN3TnpBMVdqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkxOWVYyNU1aUXRaRFE3eDAzOGdtQWYrZk43SFNhTktHZ2lLZXZIS2E2U0xU
      cFRuNWRBQwo1eDZRckEwL3ZYRm4vYUhpTktFYUtkYWc0b0tnTWtTY1dxdWpRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJTRXhmaWxi
      R2xhZi9FL1hIaHVEaHFIMUZxbDN6QUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcUR1bEE0MDc3
      RTVCVWJuYXA3c2FQRDNnWkJLSFcybmloQ0xrMkE2Qgpja0FDSVFETEFMR2FsZm5YaklPdGlBWktt
      ZVpScTlnZ2tYcVh2MGU3SkMyQkk2Q3hzdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOwoLRW5kb3JzZW1lbnQSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1JlYWRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjcKB1dyaXRlcnMSLBIiCAESHhIIEgYIARICCAAaEhIQCg5zdXBwbHljaGFpbk1T
      UBoGQWRtaW5zIjgKBkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQ
      EAEaBkFkbWlucyoGQWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4K
      DEJhdGNoVGltZW91dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZB
      ZG1pbnMaJgoMQ2FwYWJpbGl0aWVzEhYSDAoKCgZWMV80XzISABoGQWRtaW5zGrQSCg1Db25zZW5z
      dXNUeXBlEqISEpcSCghldGNkcmFmdBKKEgrzEQoqb3JkZXJlcjMuc3VwcGx5Y2hhaW4tbmV0LnN2
      Yy5jbHVzdGVyLmxvY2FsEPtBGt8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREREND
      QXJPZ0F3SUJBZ0lVSDZ5a3ZIOEJvcWZkc2tXSTZVNXdLN29TRlJBd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EY3hNVEF3V2hjTk1qRXhNVEF6TURjeE5qQXdX
      akJ1TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVa
      Rzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVEwdwpDd1lEVlFRTEV3UndaV1Z5TVNFd0h3WURW
      UVFERXhodmNtUmxjbVZ5TXk1emRYQndiSGxqYUdGcGJpMXVaWFF3CldUQVRCZ2NxaGtqT1BRSUJC
      Z2dxaGtqT1BRTUJCd05DQUFSNzRrd3phRXFYSnprUk9wSXB1cE5xZHZOQ2M0ZWoKaHR1L3Vvay9T
      WlliZ0c3OU1ZZnNZeTl3d1UxL3JwL0xlOXZQZFJtbjE3NVFxYXd3R285MXhqWkhvNElCUFRDQwpB
      VGt3RGdZRFZSMFBBUUgvQkFRREFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJn
      RUZCUWNECkFqQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSMUxTdDZRempKSW9LMTl3
      VDF0NTBXR2R5VVlqQWYKQmdOVkhTTUVHREFXZ0JTRXhmaWxiR2xhZi9FL1hIaHVEaHFIMUZxbDN6
      QlBCZ05WSFJFRVNEQkdnaGh2Y21SbApjbVZ5TXk1emRYQndiSGxqYUdGcGJpMXVaWFNDS205eVpH
      VnlaWEl6TG5OMWNIQnNlV05vWVdsdUxXNWxkQzV6CmRtTXVZMngxYzNSbGNpNXNiMk5oYkRCcEJn
      Z3FBd1FGQmdjSUFRUmRleUpoZEhSeWN5STZleUpvWmk1QlptWnAKYkdsaGRHbHZiaUk2SWlJc0lt
      aG1Ma1Z1Y205c2JHMWxiblJKUkNJNkltOXlaR1Z5WlhJekxuTjFjSEJzZVdObwpZV2x1TFc1bGRD
      SXNJbWhtTGxSNWNHVWlPaUp3WldWeUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR21vCjNF
      MFRCT216bjRyRXZ3UmxvVnBXbXBCeEZudGxFcHl2SXZ4WUJZZmxBaUFQck5GeWJSa2Y0WUY5dHVw
      RmVEOG4KSS9PZ0djMzd6QTR4WE1HamRPdlhMQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      It8ILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQXJPZ0F3SUJBZ0lVSDZ5a3ZI
      OEJvcWZkc2tXSTZVNXdLN29TRlJBd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3Ckho
      Y05NakF4TVRBek1EY3hNVEF3V2hjTk1qRXhNVEF6TURjeE5qQXdXakJ1TVFzd0NRWURWUVFHRXdK
      SFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdk
      UGNtUmxjbVZ5TVEwdwpDd1lEVlFRTEV3UndaV1Z5TVNFd0h3WURWUVFERXhodmNtUmxjbVZ5TXk1
      emRYQndiSGxqYUdGcGJpMXVaWFF3CldUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFS
      NzRrd3phRXFYSnprUk9wSXB1cE5xZHZOQ2M0ZWoKaHR1L3Vvay9TWlliZ0c3OU1ZZnNZeTl3d1Ux
      L3JwL0xlOXZQZFJtbjE3NVFxYXd3R285MXhqWkhvNElCUFRDQwpBVGt3RGdZRFZSMFBBUUgvQkFR
      REFnT29NQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNECkFqQU1CZ05WSFJN
      QkFmOEVBakFBTUIwR0ExVWREZ1FXQkJSMUxTdDZRempKSW9LMTl3VDF0NTBXR2R5VVlqQWYKQmdO
      VkhTTUVHREFXZ0JTRXhmaWxiR2xhZi9FL1hIaHVEaHFIMUZxbDN6QlBCZ05WSFJFRVNEQkdnaGh2
      Y21SbApjbVZ5TXk1emRYQndiSGxqYUdGcGJpMXVaWFNDS205eVpHVnlaWEl6TG5OMWNIQnNlV05v
      WVdsdUxXNWxkQzV6CmRtTXVZMngxYzNSbGNpNXNiMk5oYkRCcEJnZ3FBd1FGQmdjSUFRUmRleUpo
      ZEhSeWN5STZleUpvWmk1QlptWnAKYkdsaGRHbHZiaUk2SWlJc0ltaG1Ma1Z1Y205c2JHMWxiblJK
      UkNJNkltOXlaR1Z5WlhJekxuTjFjSEJzZVdObwpZV2x1TFc1bGRDSXNJbWhtTGxSNWNHVWlPaUp3
      WldWeUluMTlNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJR21vCjNFMFRCT216bjRyRXZ3UmxvVnBX
      bXBCeEZudGxFcHl2SXZ4WUJZZmxBaUFQck5GeWJSa2Y0WUY5dHVwRmVEOG4KSS9PZ0djMzd6QTR4
      WE1HamRPdlhMQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEhIKBTUwMG1zEAoYASAFKICA
      gAgaBkFkbWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIK
      B1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zKgZBZG1pbnMS
      +iMKC0NvbnNvcnRpdW1zEuojEp8jChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0ShSMSpyIKCmNhcnJp
      ZXJNU1ASmCIatCAKA01TUBKsIBKhIBKeIAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVVMSWR4K3hwM2E5OHNSWDhlTkdhbWNrNXRI
      MHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZR
      WURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNd056QTNNVFJhRncweU16
      QTRNalF3TnpBM01UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2Iy
      NHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0Ex
      VUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      QwpBQVFQdEVNekV5VmlKdlJkNnEyTXhJdDRvODJXVWdPRzhQWUI3NmtYbkZEdkxDOFJPdDErcnp6
      c3ljS2E1TnQ3Cm9PcjNMNGdSSzlOZnJnSU4wYlAxang4Rm8wSXdRREFQQmdOVkhSTUJBZjhFQlRB
      REFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVYzBNSEZua0l3SG5oWkVl
      MzBkV3cvYWUya1hnd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTHEwUmFBTUdLbE9uYTVRRzEy
      ZURZMk9EbytRcGh2NTFlY25Vd1I1QzB1WEFpQjVvRXBXCjFmTUYyNkdBVWpxNjR0NDFRNkxZM0tF
      NTVOSlljMHAwWEtTSzlRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzd6Q0NBcGFnQXdJQkFnSVVabkpFVnl3Y0QyZTNldGcxalh4
      T2xBVUdPOG93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdOekV4TURC
      YUZ3MHlNVEV4TURNd056RTJNREJhTUhreEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEh6QU5CZ05W
      CkJBc1RCbU5zYVdWdWREQU9CZ05WQkFzVEIyTmhjbkpwWlhJeEdqQVlCZ05WQkFNTUVVRmtiV2x1
      UUdOaGNuSnAKWlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUV5U0ZZ
      VzUzMzN2SDE5bTZVNDAxTgp4b25vWEZuVmdCMEVxTmdMVGdjQlh1NS9XSyszRm44Ui9vREk4Q1F5
      bHkxTFZHdXV5N3E2SkdUS2lISW1lTG1OCkdhT0NBUmt3Z2dFVk1BNEdBMVVkRHdFQi93UUVBd0lI
      Z0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVcKQkJSYXR0S1JwUjhuMzhlN0JlRzdQNk9B
      YU9mWnZEQWZCZ05WSFNNRUdEQVdnQlJ6UXdjV2VRakFlZUZrUjdmUgoxYkQ5cDdhUmVEQWtCZ05W
      SFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyT1dRM09EZzFaamcyTFRaMmNtWjRNSUdPCkJnZ3FBd1FG
      QmdjSUFRU0JnWHNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHUK
      SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWTJGeWNtbGxjaUlzSW1obUxrVnVj
      bTlzYkcxbApiblJKUkNJNklrRmtiV2x1UUdOaGNuSnBaWEl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJ
      bU5zYVdWdWRDSjlmVEFLCkJnZ3Foa2pPUFFRREFnTkhBREJFQWlCNDBDdTkrSkwycjNRVXlFZjNT
      WGs4QW1jU0lSdnVTd3ZsM09LWmRLN2sKVFFJZ2QzQXRUbTc2TjVyRjNZWUNxNWI1Y2c3cGl3QTk1
      NkxEemxRcjRUT2pENDA9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1
      NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVVMSWR4
      K3hwM2E5OHNSWDhlTkdhbWNrNXRIMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpN
      REV4TURNd056QTNNVFJhRncweU16QTRNalF3TnpBM01UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01R
      OHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNn
      d0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhr
      ak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFQdEVNekV5VmlKdlJkNnEyTXhJdDRvODJXVWdPRzhQ
      WUI3NmtYbkZEdkxDOFJPdDErcnp6c3ljS2E1TnQ3Cm9PcjNMNGdSSzlOZnJnSU4wYlAxang4Rm8w
      SXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhR
      NEVGZ1FVYzBNSEZua0l3SG5oWkVlMzBkV3cvYWUya1hnd0NnWUlLb1pJemowRQpBd0lEU0FBd1JR
      SWhBTHEwUmFBTUdLbE9uYTVRRzEyZURZMk9EbytRcGh2NTFlY25Vd1I1QzB1WEFpQjVvRXBXCjFm
      TUYyNkdBVWpxNjR0NDFRNkxZM0tFNTVOSlljMHAwWEtTSzlRPT0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpa7gsIARL0BQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0Fa
      NmdBd0lCQWdJVVVMSWR4K3hwM2E5OHNSWDhlTkdhbWNrNXRIMHdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdW
      eUxXNWxkREFlRncweQpNREV4TURNd056QTNNVFJhRncweU16QTRNalF3TnpBM01UUmFNRm94Q3pB
      SkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1S
      dmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVFQdEVNekV5VmlKdlJkNnEy
      TXhJdDRvODJXVWdPRzhQWUI3NmtYbkZEdkxDOFJPdDErcnp6c3ljS2E1TnQ3Cm9PcjNMNGdSSzlO
      ZnJnSU4wYlAxang4Rm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dR
      RUF3SUJwakFkQmdOVkhRNEVGZ1FVYzBNSEZua0l3SG5oWkVlMzBkV3cvYWUya1hnd0NnWUlLb1pJ
      emowRQpBd0lEU0FBd1JRSWhBTHEwUmFBTUdLbE9uYTVRRzEyZURZMk9EbytRcGh2NTFlY25Vd1I1
      QzB1WEFpQjVvRXBXCjFmTUYyNkdBVWpxNjR0NDFRNkxZM0tFNTVOSlljMHAwWEtTSzlRPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBmNsaWVudBryBQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVVVMSWR4K3hwM2E5OHNSWDhlTkdhbWNrNXRIMHdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNd056QTNNVFJhRncweU16QTRN
      alF3TnpBM01UUmFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVFQdEVNekV5VmlKdlJkNnEyTXhJdDRvODJXVWdPRzhQWUI3NmtYbkZEdkxDOFJPdDErcnp6c3lj
      S2E1TnQ3Cm9PcjNMNGdSSzlOZnJnSU4wYlAxang4Rm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVYzBNSEZua0l3SG5oWkVlMzBk
      V3cvYWUya1hnd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTHEwUmFBTUdLbE9uYTVRRzEyZURZ
      Mk9EbytRcGh2NTFlY25Vd1I1QzB1WEFpQjVvRXBXCjFmTUYyNkdBVWpxNjR0NDFRNkxZM0tFNTVO
      SlljMHAwWEtTSzlRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBHBlZXIaBkFkbWlucyIz
      CgdSZWFkZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dy
      aXRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5z
      EioSIAgBEhwSCBIGCAESAggAGhASDgoKY2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1l
      bnQSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2FwYWJpbGl0
      aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEy
      NTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5z
      GmAKEE9yZGVyZXJBZGRyZXNzZXMSTBIxCi9vcmRlcmVyMy5zdXBwbHljaGFpbi1uZXQuc3ZjLmNs
      dXN0ZXIubG9jYWw6ODQ0MxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiIgoGQWRtaW5zEhgSDggD
      EgoKBkFkbWlucxACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMi
      IgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoA
      CgA=
