apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIMq4pglz1aNYw/+NpKd5gAOF0tQrz1vWihKz63q55/I8Ep9TCpxTCplTCngKWggBEAEaBgjl
      roX9BSIKc3lzY2hhbm5lbCpAMDk1NjNmYTkxYjczZDZjMTNlN2RiMGQ5OWJhNTdmMzAxM2E1MWUw
      OTU2ZDNkMDZjMGYxZWJjNWU5YWUwMWE5NhIaEhicGKkiBVxnt/xQoOldLbt5FS+nCHUw8FoSnFIK
      mVISllIS+iMKC0NvbnNvcnRpdW1zEuojEp8jChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0ShSMSpyIK
      CmNhcnJpZXJNU1ASmCIatCAKA01TUBKsIBKhIBKeIAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWJTMFVWbFFlZS82YVRRWUl6VDVy
      SUhzMU1EMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5
      TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNeE16QXpORGxh
      RncweU16QTRNalF4TXpBek5EbGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpN
      YjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgK
      TUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQwpBQVNQR0dVSk1ISmdhWTViMDI1Z09qcVFZdy9iRXNBOVNzVkpXaUwwKy9yRUpvNm5u
      QXFCRy9UbVNZZ29oL2ZoCk5xOUtYT3llcE5jVytCS24wSGZPSlR5SW8wSXdRREFQQmdOVkhSTUJB
      ZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVV2dTTzRna3lW
      dGpMSENaZTUybHRBTkJJN3VZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS3Izb0tqeVdkbWF2
      ZEV4ZEJ4Rk43cUhpbk1GYnZVOVpaS2hDeFRDT3MxK0FpQjhUTFBNCkhSbkhHQkxidUxpRlBsZEFn
      QWR0UnowdVFFTkQrMEJLRFd0ajNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQzhEQ0NBcGFnQXdJQkFnSVVKR3VXa20wazRWZThQ
      VmRuS2RVd1pxRy9HaW93Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXhN
      ekE0TURCYUZ3MHlNVEV4TURNeE16RXpNREJhTUhreEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApW
      UVFIRXhJMU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEh6
      QU5CZ05WCkJBc1RCbU5zYVdWdWREQU9CZ05WQkFzVEIyTmhjbkpwWlhJeEdqQVlCZ05WQkFNTUVV
      RmtiV2x1UUdOaGNuSnAKWlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFn
      QUU4TkVtTjliSktucmJZOG84WHpTbAp2LzdBNFFNajFUb2FyYktQQW5rYVRIbldKQS9oU0xqWDlE
      WEJHV2JvQTZvV3pLVUdvWS8reWJoQmh3S3htQWx0Cmc2T0NBUmt3Z2dFVk1BNEdBMVVkRHdFQi93
      UUVBd0lIZ0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVcKQkJTODdrd09JRGliVVNITlJV
      cGhZWE1KSE9ncW9UQWZCZ05WSFNNRUdEQVdnQlJhQkk3aUNUSlcyTXNjSmw3bgphVzBBMEVqdTVq
      QWtCZ05WSFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyT1dRM09EZzFaamcyTFRSMmMydHNNSUdPCkJn
      Z3FBd1FGQmdjSUFRU0JnWHNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1G
      a2JXbHUKSWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWTJGeWNtbGxjaUlzSW1o
      bUxrVnVjbTlzYkcxbApiblJKUkNJNklrRmtiV2x1UUdOaGNuSnBaWEl0Ym1WMElpd2lhR1l1Vkhs
      d1pTSTZJbU5zYVdWdWRDSjlmVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXhoOUtFelFYQ1Vl
      REsyTGM3YVBsMFhXZlFhc09uUmpVTEUrcjhvKzgKL2swQ0lBT1R3RHJtZ0pHKytYdElpOEM0Q1ov
      dnY5M3BUTHZ3R283a2NYcEFQYXcvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTIS
      BlNIQTI1NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJ
      VWJTMFVWbFFlZS82YVRRWUl6VDVySUhzMU1EMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFV
      RUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJB
      d0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFl
      RncweQpNREV4TURNeE16QXpORGxhRncweU16QTRNalF4TXpBek5EbGFNRm94Q3pBSkJnTlZCQVlU
      QWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRH
      QTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNQR0dVSk1ISmdhWTViMDI1Z09qcVFZdy9i
      RXNBOVNzVkpXaUwwKy9yRUpvNm5uQXFCRy9UbVNZZ29oL2ZoCk5xOUtYT3llcE5jVytCS24wSGZP
      SlR5SW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFk
      QmdOVkhRNEVGZ1FVV2dTTzRna3lWdGpMSENaZTUybHRBTkJJN3VZd0NnWUlLb1pJemowRQpBd0lE
      U0FBd1JRSWhBS3Izb0tqeVdkbWF2ZEV4ZEJ4Rk43cUhpbk1GYnZVOVpaS2hDeFRDT3MxK0FpQjhU
      TFBNCkhSbkhHQkxidUxpRlBsZEFnQWR0UnowdVFFTkQrMEJLRFd0ajNBPT0KLS0tLS1FTkQgQ0VS
      VElGSUNBVEUtLS0tLQpa7gsIARL0BQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlC
      K0RDQ0FaNmdBd0lCQWdJVWJTMFVWbFFlZS82YVRRWUl6VDVySUhzMU1EMHdDZ1lJS29aSXpqMEVB
      d0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVC
      d3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZ
      WEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNeE16QXpORGxhRncweU16QTRNalF4TXpBek5EbGFN
      Rm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01C
      a3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnlj
      bWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVNQR0dVSk1ISmdh
      WTViMDI1Z09qcVFZdy9iRXNBOVNzVkpXaUwwKy9yRUpvNm5uQXFCRy9UbVNZZ29oL2ZoCk5xOUtY
      T3llcE5jVytCS24wSGZPSlR5SW8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3
      RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVV2dTTzRna3lWdGpMSENaZTUybHRBTkJJN3VZd0Nn
      WUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS3Izb0tqeVdkbWF2ZEV4ZEJ4Rk43cUhpbk1GYnZVOVpa
      S2hDeFRDT3MxK0FpQjhUTFBNCkhSbkhHQkxidUxpRlBsZEFnQWR0UnowdVFFTkQrMEJLRFd0ajNB
      PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBmNsaWVudBryBQrpBS0tLS0tQkVHSU4gQ0VS
      VElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWJTMFVWbFFlZS82YVRRWUl6VDVySUhz
      MU1EMHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4
      dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJj
      d0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNeE16QXpORGxhRncw
      eU16QTRNalF4TXpBek5EbGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1
      a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJV
      R0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1C
      QndOQwpBQVNQR0dVSk1ISmdhWTViMDI1Z09qcVFZdy9iRXNBOVNzVkpXaUwwKy9yRUpvNm5uQXFC
      Ry9UbVNZZ29oL2ZoCk5xOUtYT3llcE5jVytCS24wSGZPSlR5SW8wSXdRREFQQmdOVkhSTUJBZjhF
      QlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVV2dTTzRna3lWdGpM
      SENaZTUybHRBTkJJN3VZd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBS3Izb0tqeVdkbWF2ZEV4
      ZEJ4Rk43cUhpbk1GYnZVOVpaS2hDeFRDT3MxK0FpQjhUTFBNCkhSbkhHQkxidUxpRlBsZEFnQWR0
      UnowdVFFTkQrMEJLRFd0ajNBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBHBlZXIaBkFk
      bWlucyIzCgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5z
      IjQKBkFkbWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcK
      C0VuZG9yc2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMK
      B1JlYWRlcnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlu
      cxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRl
      cmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIA
      GhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMSwSsKB09y
      ZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQSsRQKDnN1cHBseWNo
      YWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBRENDQWFhZ0F3SUJBZ0lV
      SDhnS3FRZjlrcXdEYnJwbVNnbWpta1VybHJJd0NnWUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVF
      QmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3
      RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVa
      WFF3CkhoY05NakF4TVRBek1UTXdNek01V2hjTk1qTXdPREkwTVRNd016TTVXakJlTVFzd0NRWURW
      UVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhEQVpNYjI1a2IyNHhF
      REFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFjSEJzZVdOb1lXbHVM
      VzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJOGp4a2hnLzlFcHFEMjhB
      aXhOZVh5TTB5eFZWYkF6c0YzbWI3WjZBY0dDK3hKeE1sWDIKT0JLbXFsNUtMbzRjM1RJbDZiWERL
      UUdFcC9oYTdrUW5mcEdqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEZ1lEVlIwUEFRSC9C
      QVFEQWdHbU1CMEdBMVVkRGdRV0JCUXQzNUJWMkN0Nm5CQStLOXlpZzRid2hWWnE5REFLCkJnZ3Fo
      a2pPUFFRREFnTklBREJGQWlFQXZqMG1JSmVVYTllY3l5aGVqcG9kK1RCbW5paG4zQ3FOWmhPaDZN
      VVIKZXpRQ0lBV2FrZGloSVNvZ21VbjM2WFRpRE1nYkx1Q1lLTFNBYkZwTGFkWng5ZzluCi0tLS0t
      RU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1
      RENDQW9xZ0F3SUJBZ0lVSkErVEozZ2R5YlZqeHE4aVBpTTV2ZXdMUTVjd0NnWUlLb1pJemowRUF3
      SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3
      d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRY
      QndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1UTXdOekF3V2hjTk1qRXhNVEF6TVRNeE1q
      QXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5UQXZMVEF1TVRNdlRH
      OXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3WmpiR2xsYm5ReEhq
      QWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1CTUdCeXFHU000OUFn
      RUdDQ3FHU000OUF3RUhBMElBQkZMTnU3dGQ1YkRxSW9laUNhTXZtbzZiYitnUWlVUVoKcDhEcEV4
      MHZ1QndwRFhVWTBPdVFJamJUNXdqSVkzZ0RleXZQWGRTaDlJa2grZDZKZDdZMHplV2pnZ0VWTUlJ
      QgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURBZEJnTlZIUTRFRmdR
      VSs4eWdsQkJLCjJGOVplYzFPL3l5ckZLeVdNd293SHdZRFZSMGpCQmd3Rm9BVUxkK1FWZGdyZXB3
      UVBpdmNvb09HOElWV2F2UXcKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhNdE5qbGtOemc0TldZ
      NE5pMXNlR0pvWnpDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1s
      MElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpv
      aUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4NVkyaGhhVzR0Ym1W
      MElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFEQWdOSQpBREJGQWlF
      QWdscWVBMmJNTjNjUis4UVZ2ZUNOMVpJRmVqeFZXQnlZOW9nTDh6cXRidzhDSUIxTCtBOUUraVo5
      CkY5Q3Q5czBUeXhhNnI0MkRtMjBhNFo2KzNKNHNvUHJrCi0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDQURD
      Q0FhYWdBd0lCQWdJVUg4Z0txUWY5a3F3RGJycG1TZ21qbWtVcmxySXdDZ1lJS29aSXpqMEVBd0l3
      ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dH
      VEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3
      YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNVE13TXpNNVdoY05Nak13T0RJME1UTXdNek01
      V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1TVE4d0RRWURWUVFI
      REFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05WQkFNTUVtTmhMbk4x
      Y0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCSThq
      eGtoZy85RXBxRDI4QWl4TmVYeU0weXhWVmJBenNGM21iN1o2QWNHQyt4SnhNbFgyCk9CS21xbDVL
      TG80YzNUSWw2YlhES1FHRXAvaGE3a1FuZnBHalFqQkFNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHcK
      RGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlF0MzVCVjJDdDZuQkErSzl5aWc0Yndo
      VlpxOURBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpRUF2ajBtSUplVWE5ZWN5eWhlanBvZCtUQm1u
      aWhuM0NxTlpoT2g2TVVSCmV6UUNJQVdha2RpaElTb2dtVW4zNlhUaURNZ2JMdUNZS0xTQWJGcExh
      ZFp4OWc5bgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgKBkFkbWlucxIuEiQI
      ARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7CgtFbmRvcnNlbWVu
      dBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHUmVhZGVy
      cxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMiNwoHV3JpdGVy
      cxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1pbnMqBkFkbWlucxom
      CgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMhIAGgZBZG1pbnMatBIKDUNvbnNlbnN1c1R5cGUS
      ohISlxIKCGV0Y2RyYWZ0EooSCvMRCipvcmRlcmVyMy5zdXBwbHljaGFpbi1uZXQuc3ZjLmNsdXN0
      ZXIubG9jYWwQ+0Ea3wgtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRERUQ0NBck9nQXdJ
      QkFnSVVDNllmVTMzKzJOWncvcVhlZDFTRklPRGtrdnd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFr
      R0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1
      Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0Zw
      YmkxdVpYUXcKSGhjTk1qQXhNVEF6TVRNd09EQXdXaGNOTWpFeE1UQXpNVE14TXpBd1dqQnVNUXN3
      Q1FZRFZRUUdFd0pIUWpFYgpNQmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3
      RGdZRFZRUUtFd2RQY21SbGNtVnlNUTB3CkN3WURWUVFMRXdSd1pXVnlNU0V3SHdZRFZRUURFeGh2
      Y21SbGNtVnlNeTV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKV1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pP
      UFFNQkJ3TkNBQVR2OFdhRERPR0JUMjlIQVVDaXZzWmNnQkh6aUhsUwpvNmQvcWd2TkVKYW0waG5H
      N0xibzVZbVZhMGxGMDhBd2g3SW9XcmVqaVMxK20wcXlRNWRldTU2Rm80SUJQVENDCkFUa3dEZ1lE
      VlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0QK
      QWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJvdmV2SnJNbU52V0thYXdvT3VkY1p2
      Y1UzdVRBZgpCZ05WSFNNRUdEQVdnQlF0MzVCVjJDdDZuQkErSzl5aWc0YndoVlpxOURCUEJnTlZI
      UkVFU0RCR2doaHZjbVJsCmNtVnlNeTV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NLbTl5WkdWeVpYSXpM
      bk4xY0hCc2VXTm9ZV2x1TFc1bGRDNXoKZG1NdVkyeDFjM1JsY2k1c2IyTmhiREJwQmdncUF3UUZC
      Z2NJQVFSZGV5SmhkSFJ5Y3lJNmV5Sm9aaTVCWm1acApiR2xoZEdsdmJpSTZJaUlzSW1obUxrVnVj
      bTlzYkcxbGJuUkpSQ0k2SW05eVpHVnlaWEl6TG5OMWNIQnNlV05vCllXbHVMVzVsZENJc0ltaG1M
      bFI1Y0dVaU9pSndaV1Z5SW4xOU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ1IKZlJjUXhxdTR5
      THIzNXNaRzVjWkpTTUU2VDZpaXBBSU56cUdMWTB4cWl3SWdTK0VoQnVKT0JCS0llVklyMUVxVAps
      ZHpmL2d0ZFFSLzZOZFR3WHpKTjVURT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoi3wgtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRERUQ0NBck9nQXdJQkFnSVVDNllmVTMzKzJOWncv
      cVhlZDFTRklPRGtrdnd3Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBj
      bVJsY21WeU1Sc3dHUVlEVlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qQXhN
      VEF6TVRNd09EQXdXaGNOTWpFeE1UQXpNVE14TXpBd1dqQnVNUXN3Q1FZRFZRUUdFd0pIUWpFYgpN
      QmtHQTFVRUJ4TVNOVEV1TlRBdkxUQXVNVE12VEc5dVpHOXVNUkF3RGdZRFZRUUtFd2RQY21SbGNt
      VnlNUTB3CkN3WURWUVFMRXdSd1pXVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNeTV6ZFhCd2JI
      bGphR0ZwYmkxdVpYUXcKV1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVR2OFdhRERP
      R0JUMjlIQVVDaXZzWmNnQkh6aUhsUwpvNmQvcWd2TkVKYW0waG5HN0xibzVZbVZhMGxGMDhBd2g3
      SW9XcmVqaVMxK20wcXlRNWRldTU2Rm80SUJQVENDCkFUa3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01C
      MEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0QKQWpBTUJnTlZIUk1CQWY4RUFq
      QUFNQjBHQTFVZERnUVdCQlJvdmV2SnJNbU52V0thYXdvT3VkY1p2Y1UzdVRBZgpCZ05WSFNNRUdE
      QVdnQlF0MzVCVjJDdDZuQkErSzl5aWc0YndoVlpxOURCUEJnTlZIUkVFU0RCR2doaHZjbVJsCmNt
      VnlNeTV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NLbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm9ZV2x1TFc1
      bGRDNXoKZG1NdVkyeDFjM1JsY2k1c2IyTmhiREJwQmdncUF3UUZCZ2NJQVFSZGV5SmhkSFJ5Y3lJ
      NmV5Sm9aaTVCWm1acApiR2xoZEdsdmJpSTZJaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SW05
      eVpHVnlaWEl6TG5OMWNIQnNlV05vCllXbHVMVzVsZENJc0ltaG1MbFI1Y0dVaU9pSndaV1Z5SW4x
      OU1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ1IKZlJjUXhxdTR5THIzNXNaRzVjWkpTTUU2VDZp
      aXBBSU56cUdMWTB4cWl3SWdTK0VoQnVKT0JCS0llVklyMUVxVApsZHpmL2d0ZFFSLzZOZFR3WHpK
      TjVURT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSEgoFNTAwbXMQChgBIAUogICACBoGQWRt
      aW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91dBIO
      EgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0
      ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGmAKEE9yZGVyZXJBZGRyZXNzZXMSTBIxCi9vcmRlcmVyMy5zdXBwbHljaGFpbi1u
      ZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODQ0MxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1p
      bnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zIiIKB1dyaXRl
      cnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
