apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIAyd13ln2awT4HODnhwGubFwA7ItIqQbBnLmSK9bKYUnEp9TCpxTCplTCngKWggBEAEaBgib
      pYT9BSIKc3lzY2hhbm5lbCpAZmUwZDhjYmIwNzcxZTIyYTMxZTNjYTk4MTllOTJhNTA1MDVkYWRm
      NmFkMzU2YjNmN2MxOWMzMGRjNTVjN2FmMRIaEhijBACAEO21Z4tsW3Ocr1/fCmFjBrpotuESnFIK
      mVISllISwSsKB09yZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTUIvcXZtMUZhSUNpNmRENVlTYlVoT0l4Yjdzd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EZ3hNREEyV2hjTk1qTXdPREkwTURneE1EQTJX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJIakw1
      cE9GUW1OWHVrL2hwTHg5UTZycVN6L01qUDJRUnIzSHowblJpZ3JrTVZoYno1cnQKaXU5QzZlRTdM
      R0xnY1ZKZFozNWNmRHZncHBCQlg1Q2Q5SnFqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCU2RWWWFNcVl0SmZUTVFQUTRHaitxNEll
      aXZQREFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBVldpS2t2ZVVMNjFhcldVQUh4dDkvNWljVlAx
      enV0b3B0LzIwOSthZXMKYXdJaEFMa3FtbEthd05jSnBDUTlWWWxNbmZCMlBteXlKRjQ5dGZqbFZE
      b1FET2RJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM1RENDQW9xZ0F3SUJBZ0lVSy9MUGxwbVhWdmhHa1RlL2QydzNGL2NPQktBd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EZ3hOREF3V2hjTk1q
      RXhNVEF6TURneE9UQXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3
      WmpiR2xsYm5ReEhqQWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktTTVorUUt5bjF6bm5ZT0k4L1R5bEVIclV5
      UjM4bUIKWlRzNFhMa2wyTVRqNGVzOTNQdTNaL2loaCtmdEROMTNCbEQxekRKUnV0dHFKdlRxMHlX
      TDZxbWpnZ0VWTUlJQgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVTRzUkl3azhpClhXQnduK1psMVVTQ1BmZGx0V3d3SHdZRFZSMGpCQmd3Rm9B
      VW5WV0dqS21MU1gwekVEME9Cby9xdUNIb3J6d3cKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhN
      dE5qbGtOemc0TldZNE5pMXRabk40TlRDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25z
      aVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1s
      c2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFE
      QWdOSQpBREJGQWlFQTd0dWVKd1VXMXpwU0V1emN6bjRneGFrcnlWQmQrWmh2WUt3cW5hSVVaTmND
      SURYQzVaODBvcDViCnlKSGxvL21rM1c0Wnc0Sy9JY1JWbzdEcnMwcXR6OGtXCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVU1CL3F2bTFGYUlDaTZkRDVZU2JVaE9JeGI3c3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNRGd4TURBMldoY05Nak13
      T0RJME1EZ3hNREEyV2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCSGpMNXBPRlFtTlh1ay9ocEx4OVE2cnFTei9NalAyUVJyM0h6MG5SaWdya01WaGJ6
      NXJ0Cml1OUM2ZUU3TEdMZ2NWSmRaMzVjZkR2Z3BwQkJYNUNkOUpxalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlNkVllhTXFZdEpm
      VE1RUFE0R2orcTRJZWl2UERBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQVZXaUtrdmVVTDYxYXJX
      VUFIeHQ5LzVpY1ZQMXp1dG9wdC8yMDkrYWVzCmF3SWhBTGtxbWxLYXdOY0pwQ1E5VllsTW5mQjJQ
      bXl5SkY0OXRmamxWRG9RRE9kSQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjgK
      BkFkbWlucxIuEiQIARIgEggSBggBEgIIABoUEhIKDnN1cHBseWNoYWluTVNQEAEaBkFkbWlucyI7
      CgtFbmRvcnNlbWVudBIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHUmVhZGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMiNwoHV3JpdGVycxIsEiIIARIeEggSBggBEgIIABoSEhAKDnN1cHBseWNoYWluTVNQGgZBZG1p
      bnMqBkFkbWlucxoeCgxCYXRjaFRpbWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0
      cmljdGlvbnMSCBoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxq0EgoNQ29uc2Vuc3VzVHlwZRKiEhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBs
      eWNoYWluLW5ldC5zdmMuY2x1c3Rlci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVWFOZzdrT3E0elNBSTBENUxmbWh4dVFwUXJjVXdDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNRGd4TkRBd1doY05NakV4
      TVRBek1EZ3hPVEF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2
      TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3
      WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU0hqOGhRRHVaUDlXM1ROTXBwNFRkVmVVZmdu
      dXVLCmxxNkF2UXJrQjZEalE1bmlJUndNV21jOEl5V01kMDIveVRheE5FczU1UEo4UC9qdUFtSHJR
      T2JKbzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dB
      UVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkx6
      RVZGSm1XOUNHanppdjR6N2pScVlGVStzVEFmCkJnTlZIU01FR0RBV2dCU2RWWWFNcVl0SmZUTVFQ
      UTRHaitxNEllaXZQREJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBi
      aTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxj
      aTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhk
      R2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VX
      Tm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0Ew
      Y0FNRVFDSUFOVQprUWlwbGJiTitKbldmcFlXZW9vdW5RNWlkSWRrRWhwaVI5OHp0L2dZQWlCSmV4
      Vjlwb1YrUnpJSmI3aGQzMVJHCkwrZUtxVlYxVmZTWFp2eUJrWWxlNXc9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dB
      d0lCQWdJVWFOZzdrT3E0elNBSTBENUxmbWh4dVFwUXJjVXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNRGd4TkRBd1doY05NakV4TVRBek1EZ3hPVEF3V2pCdU1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBU0hqOGhRRHVaUDlXM1ROTXBwNFRkVmVVZmdudXVLCmxxNkF2UXJrQjZEalE1
      bmlJUndNV21jOEl5V01kMDIveVRheE5FczU1UEo4UC9qdUFtSHJRT2JKbzRJQlBUQ0MKQVRrd0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFj
      RApBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUkx6RVZGSm1XOUNHanppdjR6N2pS
      cVlGVStzVEFmCkJnTlZIU01FR0RBV2dCU2RWWWFNcVl0SmZUTVFQUTRHaitxNEllaXZQREJQQmdO
      VkhSRUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJ
      ekxuTjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdR
      RkJnY0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtW
      dWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1o
      bUxsUjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUFOVQprUWlwbGJi
      TitKbldmcFlXZW9vdW5RNWlkSWRrRWhwaVI5OHp0L2dZQWlCSmV4Vjlwb1YrUnpJSmI3aGQzMVJH
      CkwrZUtxVlYxVmZTWFp2eUJrWWxlNXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1
      MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1p
      bnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoK
      BkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5zEvojCgtDb25z
      b3J0aXVtcxLqIxKfIwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEoUjEqciCgpjYXJyaWVyTVNQEpgi
      GrQgCgNNU1ASrCASoSASniAKCmNhcnJpZXJNU1AS6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVhYWZuRmZ2ZjNLQzQvVFAyejZrdUV6bDJwNE13Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdPREV3TVRWYUZ3MHlNekE0TWpRd09E
      RXdNVFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTVHFP
      VXlHS3NoMVNyNHVtUVlWUk9QUXhjNGU3aUNUWHR0bllxOWZqNlVZOEY2elFSRjN6SkxjQlRSNzBP
      OApmLzJ3VE40SS9FVHJ0UlFENG1pRExYMzFvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWlZcWhrUnZkd0k1RE15ZGdMZ0VYZUc2
      eU9KZ3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5SMnJWY09Ec0lDRGE5YWxHOG9tYi84OUJL
      V0NONEJEWVVCN3p4SjAwVk9BaUJMcldudQpmV205clhHdk1mekhERENpL2VXUVhSNjdOQVBaaW50
      a3ZqQjRBZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIrYILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM3ekNDQXBhZ0F3SUJBZ0lVZmVMa2Y3V2o0S2Q4TnNQNDBrc2d5emg1dTRR
      d0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWREWVhKeWFXVnlNUmN3RlFZ
      RFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1ERXhNRE13T0RFME1EQmFGdzB5TVRF
      eE1ETXdPREU1TURCYU1Ia3hDekFKQmdOVkJBWVRBa2RDTVJzd0dRWUQKVlFRSEV4STFNUzQxTUM4
      dE1DNHhNeTlNYjI1a2IyNHhFREFPQmdOVkJBb1RCME5oY25KcFpYSXhIekFOQmdOVgpCQXNUQm1O
      c2FXVnVkREFPQmdOVkJBc1RCMk5oY25KcFpYSXhHakFZQmdOVkJBTU1FVUZrYldsdVFHTmhjbkpw
      ClpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFNVovcW1rcC9jNGdW
      MHNVajREQTgKMjNnL1ZYbklwSXQyd2g2UHhyWXhxQTFWL0NhRXBuWnpHYnFsUm1VSHp5Z21EdVVZ
      VmdvVWxtMU1wNXRsb1hhVwpwS09DQVJrd2dnRVZNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05W
      SFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXCkJCVG1Ibk1uQm1RYTBiT3ZLdFpNbmZoOUpVV1RBVEFm
      QmdOVkhTTUVHREFXZ0JTSmlxR1JHOTNBamtNekoyQXUKQVJkNGJySTRtREFrQmdOVkhSRUVIVEFi
      Z2hsallTMTBiMjlzY3kwMk9XUTNPRGcxWmpnMkxUazRkalZtTUlHTwpCZ2dxQXdRRkJnY0lBUVNC
      Z1hzaVlYUjBjbk1pT25zaVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1Cklqb2lkSEox
      WlNJc0ltaG1Ma0ZtWm1sc2FXRjBhVzl1SWpvaVkyRnljbWxsY2lJc0ltaG1Ma1Z1Y205c2JHMWwK
      Ym5SSlJDSTZJa0ZrYldsdVFHTmhjbkpwWlhJdGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVk
      Q0o5ZlRBSwpCZ2dxaGtqT1BRUURBZ05IQURCRUFpQlBqOENIRlJQM2NyNWNuRVNJenJmZlZTTW5P
      U09MOGtYdWVSL2YxYlM5CnhBSWdmWnl2YnYyaVc3em1sbnRHN3hWQThOR0Uvb0RRMUdHUEVkTkhG
      dC9qVDR3PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK6QUtLS0t
      LUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFnSVVhYWZuRmZ2ZjNLQzQv
      VFAyejZrdUV6bDJwNE13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5C
      Z05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZ
      WEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdP
      REV3TVRWYUZ3MHlNekE0TWpRd09ERXdNVFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApW
      UVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNt
      bGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkMKQUFTVHFPVXlHS3NoMVNyNHVtUVlWUk9QUXhjNGU3aUNUWHR0bllxOWZq
      NlVZOEY2elFSRjN6SkxjQlRSNzBPOApmLzJ3VE40SS9FVHJ0UlFENG1pRExYMzFvMEl3UURBUEJn
      TlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWlZ
      cWhrUnZkd0k1RE15ZGdMZ0VYZUc2eU9KZ3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5SMnJW
      Y09Ec0lDRGE5YWxHOG9tYi84OUJLV0NONEJEWVVCN3p4SjAwVk9BaUJMcldudQpmV205clhHdk1m
      ekhERENpL2VXUVhSNjdOQVBaaW50a3ZqQjRBZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      Wu4LCAES9AUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQitEQ0NBWjZnQXdJQkFn
      SVVhYWZuRmZ2ZjNLQzQvVFAyejZrdUV6bDJwNE13Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0Ex
      VUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1S
      QXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERB
      ZUZ3MHkKTURFeE1ETXdPREV3TVRWYUZ3MHlNekE0TWpRd09ERXdNVFZhTUZveEN6QUpCZ05WQkFZ
      VEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZiakVRTUE0
      R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVaWFF3V1RB
      VEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTVHFPVXlHS3NoMVNyNHVtUVlWUk9QUXhj
      NGU3aUNUWHR0bllxOWZqNlVZOEY2elFSRjN6SkxjQlRSNzBPOApmLzJ3VE40SS9FVHJ0UlFENG1p
      RExYMzFvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVBd0lCcGpB
      ZEJnTlZIUTRFRmdRVWlZcWhrUnZkd0k1RE15ZGdMZ0VYZUc2eU9KZ3dDZ1lJS29aSXpqMEUKQXdJ
      RFNBQXdSUUloQU5SMnJWY09Ec0lDRGE5YWxHOG9tYi84OUJLV0NONEJEWVVCN3p4SjAwVk9BaUJM
      cldudQpmV205clhHdk1mekhERENpL2VXUVhSNjdOQVBaaW50a3ZqQjRBZz09Ci0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KEgZjbGllbnQa8gUK6QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0K
      TUlJQitEQ0NBWjZnQXdJQkFnSVVhYWZuRmZ2ZjNLQzQvVFAyejZrdUV6bDJwNE13Q2dZSUtvWkl6
      ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdB
      MVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZ
      UzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdPREV3TVRWYUZ3MHlNekE0TWpRd09ERXdN
      VFZhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZC
      QWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZ
      MkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFTVHFPVXlH
      S3NoMVNyNHVtUVlWUk9QUXhjNGU3aUNUWHR0bllxOWZqNlVZOEY2elFSRjN6SkxjQlRSNzBPOApm
      LzJ3VE40SS9FVHJ0UlFENG1pRExYMzFvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0Ex
      VWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVWlZcWhrUnZkd0k1RE15ZGdMZ0VYZUc2eU9K
      Z3dDZ1lJS29aSXpqMEUKQXdJRFNBQXdSUUloQU5SMnJWY09Ec0lDRGE5YWxHOG9tYi84OUJLV0NO
      NEJEWVVCN3p4SjAwVk9BaUJMcldudQpmV205clhHdk1mekhERENpL2VXUVhSNjdOQVBaaW50a3Zq
      QjRBZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KEgRwZWVyGgZBZG1pbnMiMwoHV3JpdGVy
      cxIoEh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyI0CgZBZG1pbnMSKhIg
      CAESHBIIEgYIARICCAAaEBIOCgpjYXJyaWVyTVNQEAEaBkFkbWlucyI3CgtFbmRvcnNlbWVudBIo
      Eh4IARIaEggSBggBEgIIABoOEgwKCmNhcnJpZXJNU1AaBkFkbWlucyIzCgdSZWFkZXJzEigSHggB
      EhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENy
      ZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlucxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9D
      aGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFkbWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3Jk
      ZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0S
      EhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9ja0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////
      DxoGQWRtaW5zGmAKEE9yZGVyZXJBZGRyZXNzZXMSTBIxCi9vcmRlcmVyMy5zdXBwbHljaGFpbi1u
      ZXQuc3ZjLmNsdXN0ZXIubG9jYWw6ODQ0MxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoMQ2Fw
      YWJpbGl0aWVzEhYSDAoKCgZWMV80XzMSABoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3Jp
      dGVycxoGQWRtaW5zIiIKBkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRl
      cnMSFxINCAMSCQoHUmVhZGVycxoGQWRtaW5zKgZBZG1pbnMaDgoECgIKAAoACgAKAAoA
