apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIJlHznQPZhjkyNpEp7pLjDKjiN3l+KfzwLR+0fbN44BeEo9TCoxTColTCngKWggBEAEaBgi7
      8IP9BSIKc3lzY2hhbm5lbCpAYzhmOTdhMTVmODE5NDYwZmM4MWNmMDIzMGFlZWExYzUzMDI0NjFk
      Yjg4NGQxMjY0YTFkNGM1M2M4ZjJkOWZlNhIaEhiisgbrYcri3l3qs/bsQWQ6fzQ+fhJe/4gSjFIK
      iVIShlISwSsKB09yZGVyZXIStSsSzhYKDnN1cHBseWNoYWluTVNQErsWGscUCgNNU1ASvxQStBQS
      sRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVTUtJV2dkT1FHWGhZU1kxcUduR0hOSmdaRkRnd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EWXhOek13V2hjTk1qTXdPREkwTURZeE56TXdX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJNY0lv
      SGRuaEZ3azVHVWhYQzd6alIzeDBocE10Z3dLL0tLczFDT1pFc3BvdlV3V3N4YWwKbXJZWjZnVmRw
      NCtseUsvSzRWdkFtUndpSWVEZ056ZkZRZ1dqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVE9SbUVzakh6Y0xXak16S01PYUtIZ0JM
      YzdhVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlBYk5LWGZ6c1FYc0xWV3RPM0ZzcGJ1UnVIak1n
      cWJCQVNwYTBnMjMzSjIKOVFJaEFKUTZ2RXNJMmIzR0VDc2FiOGVGZll1TU4xSmVpc2M3VnduMVIy
      bDd4b1VECi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqYILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM1RENDQW9xZ0F3SUJBZ0lVUEVwdllZNXlVUjVrdlk2a25la1F6S3ZOY2dRd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1EWXlNVEF3V2hjTk1q
      RXhNVEF6TURZeU5qQXdXakJ0TVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE4dwpEUVlEVlFRTEV3
      WmpiR2xsYm5ReEhqQWNCZ05WQkFNTUZVRmtiV2x1UUhOMWNIQnNlV05vWVdsdUxXNWxkREJaCk1C
      TUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkxNdEg4eC8xYllvRkJTVlh6dzRRQ1J2Sml4
      ZHA1NEMKYUFnemFTUmFkRUEyT0ZsaXdJT24zR1Rvd3lSTmNaN3JBSnhoTXJGNWw1L2xBaUdja2Zw
      WE9OeWpnZ0VWTUlJQgpFVEFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEQVlEVlIwVEFRSC9CQUl3QURB
      ZEJnTlZIUTRFRmdRVWZ2QXYwZjlNCjlGSVhHcTFYVEJ1OVZ0a2I5Mzh3SHdZRFZSMGpCQmd3Rm9B
      VXprWmhMSXg4M0Mxb3pNeWpEbWloNEFTM08ya3cKSkFZRFZSMFJCQjB3RzRJWlkyRXRkRzl2YkhN
      dE5qbGtOemc0TldZNE5pMXlabXd5Y1RDQmlnWUlLZ01FQlFZSApDQUVFZm5zaVlYUjBjbk1pT25z
      aVlXSmhZeTVwYm1sMElqb2lkSEoxWlNJc0ltRmtiV2x1SWpvaWRISjFaU0lzCkltaG1Ma0ZtWm1s
      c2FXRjBhVzl1SWpvaUlpd2lhR1l1Ulc1eWIyeHNiV1Z1ZEVsRUlqb2lRV1J0YVc1QWMzVncKY0d4
      NVkyaGhhVzR0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlmVEFLQmdncWhrak9QUVFE
      QWdOSQpBREJGQWlFQXhnRUdsWkxyOHNGb016d1FuT2ZYOEtJdlNiRW9SOG53eU9IZ2xETk5xRndD
      SUZ3d2h6dmIwci8zCjM2QWtNUXd3dC9IclpSalB4S1ZONkNVanQyN24yaDhVCi0tLS0tRU5EIENF
      UlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrxBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlDQURDQ0FhYWdBd0lCQWdJVU1LSVdnZE9RR1hoWVNZMXFHbkdITkpnWkZEZ3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNRFl4TnpNd1doY05Nak13
      T0RJME1EWXhOek13V2pCZU1Rc3dDUVlEVlFRR0V3SkhRakVQCk1BMEdBMVVFQ0F3R1RHOXVaRzl1
      TVE4d0RRWURWUVFIREFaTWIyNWtiMjR4RURBT0JnTlZCQW9NQjA5eVpHVnkKWlhJeEd6QVpCZ05W
      QkFNTUVtTmhMbk4xY0hCc2VXTm9ZV2x1TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5
      QXdFSEEwSUFCTWNJb0hkbmhGd2s1R1VoWEM3empSM3gwaHBNdGd3Sy9LS3MxQ09aRXNwb3ZVd1dz
      eGFsCm1yWVo2Z1ZkcDQrbHlLL0s0VnZBbVJ3aUllRGdOemZGUWdXalFqQkFNQThHQTFVZEV3RUIv
      d1FGTUFNQkFmOHcKRGdZRFZSMFBBUUgvQkFRREFnR21NQjBHQTFVZERnUVdCQlRPUm1Fc2pIemNM
      V2pNektNT2FLSGdCTGM3YVRBSwpCZ2dxaGtqT1BRUURBZ05JQURCRkFpQWJOS1hmenNRWHNMVld0
      TzNGc3BidVJ1SGpNZ3FiQkFTcGEwZzIzM0oyCjlRSWhBSlE2dkVzSTJiM0dFQ3NhYjhlRmZZdU1O
      MUplaXNjN1Z3bjFSMmw3eG9VRAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChoGQWRtaW5zIjsK
      C0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlu
      cyI4CgZBZG1pbnMSLhIkCAESIBIIEgYIARICCAAaFBISCg5zdXBwbHljaGFpbk1TUBABGgZBZG1p
      bnMqBkFkbWlucxoiCglCYXRjaFNpemUSFRILCAoQgICAMRiAgEAaBkFkbWlucxoeCgxCYXRjaFRp
      bWVvdXQSDhIECgIycxoGQWRtaW5zGh8KE0NoYW5uZWxSZXN0cmljdGlvbnMSCBoGQWRtaW5zGiYK
      DENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlucxq0EgoNQ29uc2Vuc3VzVHlwZRKi
      EhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBseWNoYWluLW5ldC5zdmMuY2x1c3Rl
      ci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lC
      QWdJVVdsbXJkakVXTUhnWFIwVXhNa2pXNisxUkpLY3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtH
      QTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUK
      TVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBi
      aTF1WlhRdwpIaGNOTWpBeE1UQXpNRFl5TVRBd1doY05NakV4TVRBek1EWXlOakF3V2pCdU1Rc3dD
      UVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdE
      Z1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZj
      bVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9Q
      UU1CQndOQ0FBU2dRU2ZCbzhCUmg0UGtjOHpYSmVtcjg1dXNMd0V0CmpKb3JwL0dVczMwU0ZRUlN0
      ZW1OZnFyZU1WMW1hTG15bGN2Q094bnNDRWY0RlNYSEp3bnlUSiszbzRJQlBUQ0MKQVRrd0RnWURW
      UjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApB
      akFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVCswZVF0cENTNWhYQmx3bnhEaVFuRmZU
      eDRLVEFmCkJnTlZIU01FR0RBV2dCVE9SbUVzakh6Y0xXak16S01PYUtIZ0JMYzdhVEJQQmdOVkhS
      RUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxu
      TjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJn
      Y0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNt
      OXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxs
      UjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNwUAoxbHZJR1FqUnNk
      RjNuaDdFYmdhRmxoc1pzOHhQNUR2K1hscUFSenpHQWlBN0Vvc2RISEkrVmhKeHhnTEw5TEhRCkdP
      NzVkdXJUN2tpR09GZEVKRksvUGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiLfCC0tLS0t
      QkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVVdsbXJkakVXTUhnWFIw
      VXhNa2pXNisxUkpLY3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJn
      TlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNt
      UmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1U
      QXpNRFl5TVRBd1doY05NakV4TVRBek1EWXlOakF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1C
      a0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21W
      eU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3Ykhs
      amFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBU2dRU2ZCbzhC
      Umg0UGtjOHpYSmVtcjg1dXNMd0V0CmpKb3JwL0dVczMwU0ZRUlN0ZW1OZnFyZU1WMW1hTG15bGN2
      Q094bnNDRWY0RlNYSEp3bnlUSiszbzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIw
      R0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpB
      QU1CMEdBMVVkRGdRV0JCVCswZVF0cENTNWhYQmx3bnhEaVFuRmZUeDRLVEFmCkJnTlZIU01FR0RB
      V2dCVE9SbUVzakh6Y0xXak16S01PYUtIZ0JMYzdhVEJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21W
      eU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVs
      ZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2
      ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5
      WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5
      TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUNwUAoxbHZJR1FqUnNkRjNuaDdFYmdhRmxoc1pzOHhQ
      NUR2K1hscUFSenpHQWlBN0Vvc2RISEkrVmhKeHhnTEw5TEhRCkdPNzVkdXJUN2tpR09GZEVKRksv
      UGc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiAgIAIGgZBZG1p
      bnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJ
      CgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoP
      QmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zEuojCgtDb25z
      b3J0aXVtcxLaIxKPIwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtEvUiEpciCgpjYXJyaWVyTVNQEogi
      GqQgCgNNU1ASnCASkSASjiAKCmNhcnJpZXJNU1AS5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0t
      LS0KTUlJQjl6Q0NBWjZnQXdJQkFnSVVlT0J4Tmx3NC9hbm12WVBmd1VIcXEwZjBCYmt3Q2dZSUtv
      Wkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1B
      MEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERB
      NWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdOakUzTXpsYUZ3MHlNekE0TWpRd05q
      RTNNemxhTUZveEN6QUpCZ05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJn
      TlZCQWNNQmt4dmJtUnZiakVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1ky
      RXVZMkZ5Y21sbGNpMXVaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUMGxW
      TWQwOUgva1FGZmdBcDlRQnZVRVk4MElzcmZFNmNheHlNL3NMaDdXc3l2eFFiYStRWndOMUszT3Fm
      bQoyZ2lLR1FjQVlxaUZybHA0bk9lNE4vRGVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0
      R0ExVWREd0VCCi93UUVBd0lCcGpBZEJnTlZIUTRFRmdRVVdOOFFUNHVlWk9aMkNpRm8wUzdYVGNv
      cWtRTXdDZ1lJS29aSXpqMEUKQXdJRFJ3QXdSQUlnR3ZpYXFLd0N4VzFwNkx5M0tPWTUxbFVyMlVJ
      dWR3QzlRamxZSFowRXR0c0NJSDVhWDlTOAo0N2ZyUytlc3VsVDRLTDhvNk1RcTFEUThlaHVqOFRD
      dURLZzYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lOIENFUlRJRklDQVRF
      LS0tLS0KTUlJQzhEQ0NBcGFnQXdJQkFnSVVGU1o1Z3hYQnlETERFMFhnOFBnd0UvQVdHM1V3Q2dZ
      SUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpF
      UE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFR
      RERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXdOakl5TURCYUZ3MHlNVEV4TURN
      d05qSTNNREJhTUhreEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJMU1TNDFNQzh0TUM0
      eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEh6QU5CZ05WCkJBc1RCbU5zYVdW
      dWREQU9CZ05WQkFzVEIyTmhjbkpwWlhJeEdqQVlCZ05WQkFNTUVVRmtiV2x1UUdOaGNuSnAKWlhJ
      dGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVPeG14blpiZXVmRGZLTi9N
      T2VGeApvc0JBQnRzOEhDbldscHBCUGx1ZEIzS3ViN0h0SmJNZ054REVjbGVocEdZalpjSXI3a28v
      ZDI5c0VBZ3d6UWVVCnU2T0NBUmt3Z2dFVk1BNEdBMVVkRHdFQi93UUVBd0lIZ0RBTUJnTlZIUk1C
      QWY4RUFqQUFNQjBHQTFVZERnUVcKQkJUYTdPOXBNM3hiNDBoZkxwTjM4QjVsU2NNNjh6QWZCZ05W
      SFNNRUdEQVdnQlJZM3hCUGk1NWs1bllLSVdqUgpMdGROeWlxUkF6QWtCZ05WSFJFRUhUQWJnaGxq
      WVMxMGIyOXNjeTAyT1dRM09EZzFaamcyTFcwNWFEWm9NSUdPCkJnZ3FBd1FGQmdjSUFRU0JnWHNp
      WVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHUKSWpvaWRISjFaU0lz
      SW1obUxrRm1abWxzYVdGMGFXOXVJam9pWTJGeWNtbGxjaUlzSW1obUxrVnVjbTlzYkcxbApiblJK
      UkNJNklrRmtiV2x1UUdOaGNuSnBaWEl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJbU5zYVdWdWRDSjlm
      VEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQTJxUEFYK2xEVGxiOXhaQURXcjQ4ZGdMRFFQZHFh
      Ym94cHlVN29IV0IKOUlBQ0lFOXJoNnE2ZlJHSmNlOXZxc3BKYnlzWVFub1VZb3FkSU40ZDVJczZN
      aHFWCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1NkrlBS0tLS0tQkVH
      SU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCOXpDQ0FaNmdBd0lCQWdJVWVPQnhObHc0L2FubXZZUGZ3
      VUhxcTBmMEJia3dDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZC
      QWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlh
      V1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNd05qRTNN
      emxhRncweU16QTRNalF3TmpFM016bGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlE
      QVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNq
      RVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQwpBQVQwbFZNZDA5SC9rUUZmZ0FwOVFCdlVFWTgwSXNyZkU2Y2F4eU0vc0xoN1dz
      eXZ4UWJhK1Fad04xSzNPcWZtCjJnaUtHUWNBWXFpRnJscDRuT2U0Ti9EZW8wSXdRREFQQmdOVkhS
      TUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVV044UVQ0
      dWVaT1oyQ2lGbzBTN1hUY29xa1FNd0NnWUlLb1pJemowRQpBd0lEUndBd1JBSWdHdmlhcUt3Q3hX
      MXA2THkzS09ZNTFsVXIyVUl1ZHdDOVFqbFlIWjBFdHRzQ0lINWFYOVM4CjQ3ZnJTK2VzdWxUNEtM
      OG82TVFxMURROGVodWo4VEN1REtnNgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tClrmCwgBEvAF
      CuUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUI5ekNDQVo2Z0F3SUJBZ0lVZU9CeE5s
      dzQvYW5tdllQZndVSHFxMGYwQmJrd0NnWUlLb1pJemowRUF3SXcKV2pFTE1Ba0dBMVVFQmhNQ1Iw
      SXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZR
      UUtEQWREWVhKeWFXVnlNUmN3RlFZRFZRUUREQTVqWVM1allYSnlhV1Z5TFc1bGREQWVGdzB5Ck1E
      RXhNRE13TmpFM016bGFGdzB5TXpBNE1qUXdOakUzTXpsYU1Gb3hDekFKQmdOVkJBWVRBa2RDTVE4
      d0RRWUQKVlFRSURBWk1iMjVrYjI0eER6QU5CZ05WQkFjTUJreHZibVJ2YmpFUU1BNEdBMVVFQ2d3
      SFEyRnljbWxsY2pFWApNQlVHQTFVRUF3d09ZMkV1WTJGeWNtbGxjaTF1WlhRd1dUQVRCZ2NxaGtq
      T1BRSUJCZ2dxaGtqT1BRTUJCd05DCkFBVDBsVk1kMDlIL2tRRmZnQXA5UUJ2VUVZODBJc3JmRTZj
      YXh5TS9zTGg3V3N5dnhRYmErUVp3TjFLM09xZm0KMmdpS0dRY0FZcWlGcmxwNG5PZTROL0RlbzBJ
      d1FEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQgovd1FFQXdJQnBqQWRCZ05WSFE0
      RUZnUVVXTjhRVDR1ZVpPWjJDaUZvMFM3WFRjb3FrUU13Q2dZSUtvWkl6ajBFCkF3SURSd0F3UkFJ
      Z0d2aWFxS3dDeFcxcDZMeTNLT1k1MWxVcjJVSXVkd0M5UWpsWUhaMEV0dHNDSUg1YVg5UzgKNDdm
      clMrZXN1bFQ0S0w4bzZNUXExRFE4ZWh1ajhUQ3VES2c2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
      LS0KEgZjbGllbnQa7gUK5QUtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQjl6Q0NBWjZn
      QXdJQkFnSVVlT0J4Tmx3NC9hbm12WVBmd1VIcXEwZjBCYmt3Q2dZSUtvWkl6ajBFQXdJdwpXakVM
      TUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVa
      Rzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdWeU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlM
      VzVsZERBZUZ3MHkKTURFeE1ETXdOakUzTXpsYUZ3MHlNekE0TWpRd05qRTNNemxhTUZveEN6QUpC
      Z05WQkFZVEFrZENNUTh3RFFZRApWUVFJREFaTWIyNWtiMjR4RHpBTkJnTlZCQWNNQmt4dmJtUnZi
      akVRTUE0R0ExVUVDZ3dIUTJGeWNtbGxjakVYCk1CVUdBMVVFQXd3T1kyRXVZMkZ5Y21sbGNpMXVa
      WFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkMKQUFUMGxWTWQwOUgva1FGZmdBcDlR
      QnZVRVk4MElzcmZFNmNheHlNL3NMaDdXc3l2eFFiYStRWndOMUszT3FmbQoyZ2lLR1FjQVlxaUZy
      bHA0bk9lNE4vRGVvMEl3UURBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUE0R0ExVWREd0VCCi93UUVB
      d0lCcGpBZEJnTlZIUTRFRmdRVVdOOFFUNHVlWk9aMkNpRm8wUzdYVGNvcWtRTXdDZ1lJS29aSXpq
      MEUKQXdJRFJ3QXdSQUlnR3ZpYXFLd0N4VzFwNkx5M0tPWTUxbFVyMlVJdWR3QzlRamxZSFowRXR0
      c0NJSDVhWDlTOAo0N2ZyUytlc3VsVDRLTDhvNk1RcTFEUThlaHVqOFRDdURLZzYKLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQoSBHBlZXIaBkFkbWlucyIzCgdSZWFkZXJzEigSHggBEhoSCBIGCAES
      AggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1dyaXRlcnMSKBIeCAESGhIIEgYIARICCAAa
      DhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMiNAoGQWRtaW5zEioSIAgBEhwSCBIGCAESAggAGhASDgoK
      Y2Fycmllck1TUBABGgZBZG1pbnMiNwoLRW5kb3JzZW1lbnQSKBIeCAESGhIIEgYIARICCAAaDhIM
      CgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVDaGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIM
      CAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucyoXL0No
      YW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0FsZ29yaXRobRISEggKBlNIQTI1NhoGQWRt
      aW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUSEBIGCP////8PGgZBZG1pbnMaYAoQT3Jk
      ZXJlckFkZHJlc3NlcxJMEjEKL29yZGVyZXIzLnN1cHBseWNoYWluLW5ldC5zdmMuY2x1c3Rlci5s
      b2NhbDo4NDQzGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlucxomCgxDYXBhYmlsaXRpZXMSFhIMCgoK
      BlYxXzRfMxIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiIgoH
      UmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0
      ZXJzGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoACgA=
