apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: supplychain-orderer3
  namespace: supplychain-net
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychain-orderer3
  chart:
    git: ssh://git@github.com/bafsunsu/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.0.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer3
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://vault.suneelbaf.svc.cluster.local:8200
      role: vault-role
      authpath: supplychain-net-auth
      secretprefix: secret/crypto/ordererOrganizations/supplychain-net/orderers/orderer3.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: haproxy
      external_url_suffix: supplychain-net.svc.cluster.local

    genesis: |-
      CiIaIObHORWbNUoxjdh0huIRmtzQUqBddnNZsb/8DhVe8OgnEqdTCqRTCqFTCngKWggBEAEaBgjS
      44T9BSIKc3lzY2hhbm5lbCpAOTIzNzE5YzI2MzZkODE1YjkzODU3MTk2MmQ1MWUxOTAzNzY3NWMy
      MjEwMjQxOGM0OTAwZjVlZjczYjg1YjViYhIaEhg1SycExQ/jI7HZvqqCbXCSElEyluuh8y8SpFIK
      oVISnlISySsKB09yZGVyZXISvSsS1hYKDnN1cHBseWNoYWluTVNQEsMWGs8UCgNNU1ASxxQSvBQS
      uRQKDnN1cHBseWNoYWluTVNQEvUFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBVEND
      QWFhZ0F3SUJBZ0lVU0JjVm44QjdLYkpsRmx0emtjYXYrRWdoMHpZd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05NakF4TVRBek1UQXlNekE1V2hjTk1qTXdPREkwTVRBeU16QTVX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJJMEJ3
      UWJIZ0JuQTNaYmRlMHFGNTZmLzgyTmR4K0VuZHQrakZwNUhZMnJONjUxOERLeTgKL1B5VDI2cjgx
      alYyNmsvcWpDZUM4ZDBWcFpsZkt4VDBXNVNqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCVFhUWGFBbG5aZFRPb2dLQUxBdTJKMFFX
      azdZREFLCkJnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTIzVi9CdjFpLzFMeDhrdmJxS2VhcThkVHNC
      UXZjYmJTdVAxSmV1cjMKc240Q0lRREZyWlBqZDRvU2xPZVp5RXlkZVcyWkt3ak1ERUhLU3lvYmpl
      aTBOR29HK1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiKmCC0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlDNURDQ0FvcWdBd0lCQWdJVUo4ZnZSOXNWUjlyYmtXTmcvb1crTERzNHlC
      QXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dR
      WURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNVEF5TnpBd1do
      Y05NakV4TVRBek1UQXpNakF3V2pCdE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05U
      RXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1ROHcKRFFZRFZR
      UUxFd1pqYkdsbGJuUXhIakFjQmdOVkJBTU1GVUZrYldsdVFITjFjSEJzZVdOb1lXbHVMVzVsZERC
      WgpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJPdWJxQzJFcUs3QkttQVE5ZXBRbXFm
      TkFkd0x1azVXCmppa0ZjUXN6d0hRYlVGalNXSlp2OW16WVN4NWk1S3BBeWZNVU9vV24xM21GTWtK
      YmY0VXhpS3VqZ2dFVk1JSUIKRVRBT0JnTlZIUThCQWY4RUJBTUNCNEF3REFZRFZSMFRBUUgvQkFJ
      d0FEQWRCZ05WSFE0RUZnUVU0UWNKSExrcgo0V3pEeE1oMDV4WUp1RDNEek9jd0h3WURWUjBqQkJn
      d0ZvQVUxMDEyZ0paMlhVenFJQ2dDd0x0aWRFRnBPMkF3CkpBWURWUjBSQkIwd0c0SVpZMkV0ZEc5
      dmJITXROamxrTnpnNE5XWTROaTE0TkdkcWJUQ0JpZ1lJS2dNRUJRWUgKQ0FFRWZuc2lZWFIwY25N
      aU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrYldsdUlqb2lkSEoxWlNJcwpJbWhtTGtG
      bVptbHNhV0YwYVc5dUlqb2lJaXdpYUdZdVJXNXliMnhzYldWdWRFbEVJam9pUVdSdGFXNUFjM1Z3
      CmNHeDVZMmhoYVc0dGJtVjBJaXdpYUdZdVZIbHdaU0k2SW1Oc2FXVnVkQ0o5ZlRBS0JnZ3Foa2pP
      UFFRREFnTkkKQURCRkFpRUEwYUJOMHlOMmoyRm5SSGNuYTZDcEYvcFYrQUZSTWRyQ3pud1pNZHdy
      WklnQ0lBS2NuRklSUUpsNQpFTHoxaW1LYUNhYXYySktSdUlsUHA2RlBsM2VyVHhLMAotLS0tLUVO
      RCBDRVJUSUZJQ0FURS0tLS0tCkIOCgRTSEEyEgZTSEEyNTZK9QUtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQ0FUQ0NBYWFnQXdJQkFnSVVTQmNWbjhCN0tiSmxGbHR6a2NhditFZ2gwell3
      Q2dZSUtvWkl6ajBFQXdJdwpYakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFnTUJreHZibVJ2
      YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZFBjbVJsY21WeU1Sc3dHUVlE
      VlFRRERCSmpZUzV6ZFhCd2JIbGphR0ZwYmkxdVpYUXcKSGhjTk1qQXhNVEF6TVRBeU16QTVXaGNO
      TWpNd09ESTBNVEF5TXpBNVdqQmVNUXN3Q1FZRFZRUUdFd0pIUWpFUApNQTBHQTFVRUNBd0dURzl1
      Wkc5dU1ROHdEUVlEVlFRSERBWk1iMjVrYjI0eEVEQU9CZ05WQkFvTUIwOXlaR1Z5ClpYSXhHekFa
      QmdOVkJBTU1FbU5oTG5OMWNIQnNlV05vWVdsdUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUcK
      U000OUF3RUhBMElBQkkwQndRYkhnQm5BM1piZGUwcUY1NmYvODJOZHgrRW5kdCtqRnA1SFkyck42
      NTE4REt5OAovUHlUMjZyODFqVjI2ay9xakNlQzhkMFZwWmxmS3hUMFc1U2pRakJBTUE4R0ExVWRF
      d0VCL3dRRk1BTUJBZjh3CkRnWURWUjBQQVFIL0JBUURBZ0dtTUIwR0ExVWREZ1FXQkJUWFRYYUFs
      blpkVE9vZ0tBTEF1MkowUVdrN1lEQUsKQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBMjNWL0J2MWkv
      MUx4OGt2YnFLZWFxOGRUc0JRdmNiYlN1UDFKZXVyMwpzbjRDSVFERnJaUGpkNG9TbE9lWnlFeWRl
      VzJaS3dqTURFSEtTeW9iamVpME5Hb0crUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZB
      ZG1pbnMiOAoGQWRtaW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoG
      QWRtaW5zIjsKC0VuZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyI3CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5N
      U1AaBkFkbWlucyoGQWRtaW5zGiYKDENhcGFiaWxpdGllcxIWEgwKCgoGVjFfNF8yEgAaBkFkbWlu
      cxq0EgoNQ29uc2Vuc3VzVHlwZRKiEhKXEgoIZXRjZHJhZnQSihIK8xEKKm9yZGVyZXIzLnN1cHBs
      eWNoYWluLW5ldC5zdmMuY2x1c3Rlci5sb2NhbBD7QRrfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUt
      LS0tLQpNSUlERERDQ0FyT2dBd0lCQWdJVVY0UVV1OGxNNXFBdDJmUDZVQmltanhNOWZWZ3dDZ1lJ
      S29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQ
      TUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFE
      REJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNVEF5TnpBd1doY05NakV4
      TVRBek1UQXpNakF3V2pCdU1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2
      TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3
      WldWeU1TRXdId1lEVlFRREV4aHZjbVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFU
      QmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQ0FBUkdFZWRldFhyLzBXTWt1MmtIVms3YVVLL2hz
      bnY1CmNyd3J1dDk2Z3N2TjlvM0NpaTM3SzJSSEN3NFFXdG5UczBSRXNxS0p3U2N3ZWpadlFDTEl1
      WkNubzRJQlBUQ0MKQVRrd0RnWURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dB
      UVVGQndNQkJnZ3JCZ0VGQlFjRApBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGNs
      bXE5bWhxRDJGdGdYbWM2SnlBbDg1MjREekFmCkJnTlZIU01FR0RBV2dCVFhUWGFBbG5aZFRPb2dL
      QUxBdTJKMFFXazdZREJQQmdOVkhSRUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBi
      aTF1WlhTQ0ttOXlaR1Z5WlhJekxuTjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxj
      aTVzYjJOaGJEQnBCZ2dxQXdRRkJnY0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhk
      R2x2YmlJNklpSXNJbWhtTGtWdWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VX
      Tm8KWVdsdUxXNWxkQ0lzSW1obUxsUjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0Ew
      Y0FNRVFDSURYTQozRTRCVmNGMUI1Skk1cksyWmF0T1VnVjV3TlkxWVJRUmlUcm1GWHJtQWlCekps
      NHd6OEpTaWdFaHFFUXQ0d2dTCmhWMnluMm14WHNlYzZPNFRNcUN5dkE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLfCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlERERDQ0FyT2dB
      d0lCQWdJVVY0UVV1OGxNNXFBdDJmUDZVQmltanhNOWZWZ3dDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpBeE1UQXpNVEF5TnpBd1doY05NakV4TVRBek1UQXpNakF3V2pCdU1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1RMHcKQ3dZRFZRUUxFd1J3WldWeU1TRXdId1lEVlFRREV4
      aHZjbVJsY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpXVEFUQmdjcWhrak9QUUlCQmdncWhr
      ak9QUU1CQndOQ0FBUkdFZWRldFhyLzBXTWt1MmtIVms3YVVLL2hzbnY1CmNyd3J1dDk2Z3N2Tjlv
      M0NpaTM3SzJSSEN3NFFXdG5UczBSRXNxS0p3U2N3ZWpadlFDTEl1WkNubzRJQlBUQ0MKQVRrd0Rn
      WURWUjBQQVFIL0JBUURBZ09vTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFj
      RApBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCVGNsbXE5bWhxRDJGdGdYbWM2SnlB
      bDg1MjREekFmCkJnTlZIU01FR0RBV2dCVFhUWGFBbG5aZFRPb2dLQUxBdTJKMFFXazdZREJQQmdO
      VkhSRUVTREJHZ2hodmNtUmwKY21WeU15NXpkWEJ3YkhsamFHRnBiaTF1WlhTQ0ttOXlaR1Z5WlhJ
      ekxuTjFjSEJzZVdOb1lXbHVMVzVsZEM1egpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQnBCZ2dxQXdR
      RkJnY0lBUVJkZXlKaGRIUnljeUk2ZXlKb1ppNUJabVpwCmJHbGhkR2x2YmlJNklpSXNJbWhtTGtW
      dWNtOXNiRzFsYm5SSlJDSTZJbTl5WkdWeVpYSXpMbk4xY0hCc2VXTm8KWVdsdUxXNWxkQ0lzSW1o
      bUxsUjVjR1VpT2lKd1pXVnlJbjE5TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURYTQozRTRCVmNG
      MUI1Skk1cksyWmF0T1VnVjV3TlkxWVJRUmlUcm1GWHJtQWlCekpsNHd6OEpTaWdFaHFFUXQ0d2dT
      CmhWMnluMm14WHNlYzZPNFRNcUN5dkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1
      MDBtcxAKGAEgBSiAgIAIGgZBZG1pbnMaIgoJQmF0Y2hTaXplEhUSCwgKEICAgDEYgIBAGgZBZG1p
      bnMaHgoMQmF0Y2hUaW1lb3V0Eg4SBAoCMnMaBkFkbWlucxofChNDaGFubmVsUmVzdHJpY3Rpb25z
      EggaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJz
      EhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIiCgZBZG1pbnMSGBIOCAMSCgoGQWRtaW5zEAIaBkFk
      bWlucyIqCg9CbG9ja1ZhbGlkYXRpb24SFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMS
      +iMKC0NvbnNvcnRpdW1zEuojEp8jChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0ShSMSpyIKCmNhcnJp
      ZXJNU1ASmCIatCAKA01TUBKsIBKhIBKeIAoKY2Fycmllck1TUBLpBS0tLS0tQkVHSU4gQ0VSVElG
      SUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWUxSndRZnBJNFB6cEZhWG5sWmRIL0FvZzB2
      OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJt
      UnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZR
      WURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNeE1ESXpNVGhhRncweU16
      QTRNalF4TURJek1UaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2Iy
      NHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0Ex
      VUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndO
      QwpBQVF3UjFJZXAwcDcrWFdqejRMZllZeGtHa2t1b1hvRURMQzl6VWE2VUp3V0g2TW8rWVNycE80
      TVpxeDAxLzh4Cnovdy9NUWFqaXRTZUNCVm5MUzg4cXNsaG8wSXdRREFQQmdOVkhSTUJBZjhFQlRB
      REFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVbC9XTk0zNXhXM1JMQzVp
      ODhONWJHSzNXK0ZNd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBUGI0bmxlVjc5MFMxTFhlT0c4
      QUhEMGtpbEoxcFd2dmRhUEhGcHZ6Z29xVUFpQW5PS2NuCjl4TDlkdEdRenEvdmIyZmpFV05RQnll
      b3NGY0dYcFBCT01Hbm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoitggtLS0tLUJFR0lO
      IENFUlRJRklDQVRFLS0tLS0KTUlJQzhEQ0NBcGFnQXdJQkFnSVVJQ1AyRHZzQzNieGFSQ1NnQ0Vu
      Tmk2SXBYMEl3Q2dZSUtvWkl6ajBFQXdJdwpXakVMTUFrR0ExVUVCaE1DUjBJeER6QU5CZ05WQkFn
      TUJreHZibVJ2YmpFUE1BMEdBMVVFQnd3R1RHOXVaRzl1Ck1SQXdEZ1lEVlFRS0RBZERZWEp5YVdW
      eU1SY3dGUVlEVlFRRERBNWpZUzVqWVhKeWFXVnlMVzVsZERBZUZ3MHkKTURFeE1ETXhNREkzTURC
      YUZ3MHlNVEV4TURNeE1ETXlNREJhTUhreEN6QUpCZ05WQkFZVEFrZENNUnN3R1FZRApWUVFIRXhJ
      MU1TNDFNQzh0TUM0eE15OU1iMjVrYjI0eEVEQU9CZ05WQkFvVEIwTmhjbkpwWlhJeEh6QU5CZ05W
      CkJBc1RCbU5zYVdWdWREQU9CZ05WQkFzVEIyTmhjbkpwWlhJeEdqQVlCZ05WQkFNTUVVRmtiV2x1
      UUdOaGNuSnAKWlhJdGJtVjBNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVkTXFV
      RkVZYzlaVk54Q1VHdThJawp6VVpSMDQvQzRRN2VmZlBMUzVpRGZhaUhQRzIyb2R3Y0pWVm44NFpU
      WjhnanlhdmpQakErMlM3T002VUVZdnl2CjlLT0NBUmt3Z2dFVk1BNEdBMVVkRHdFQi93UUVBd0lI
      Z0RBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVcKQkJRMUxad2JvUW1HaXJ2YWZJbkJJT1ZG
      dVN5dmREQWZCZ05WSFNNRUdEQVdnQlNYOVkwemZuRmJkRXNMbUx6dwozbHNZcmRiNFV6QWtCZ05W
      SFJFRUhUQWJnaGxqWVMxMGIyOXNjeTAyT1dRM09EZzFaamcyTFRaamJUVm5NSUdPCkJnZ3FBd1FG
      QmdjSUFRU0JnWHNpWVhSMGNuTWlPbnNpWVdKaFl5NXBibWwwSWpvaWRISjFaU0lzSW1Ga2JXbHUK
      SWpvaWRISjFaU0lzSW1obUxrRm1abWxzYVdGMGFXOXVJam9pWTJGeWNtbGxjaUlzSW1obUxrVnVj
      bTlzYkcxbApiblJKUkNJNklrRmtiV2x1UUdOaGNuSnBaWEl0Ym1WMElpd2lhR1l1Vkhsd1pTSTZJ
      bU5zYVdWdWRDSjlmVEFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlFQXNjeWovMEkxMnZpNmVkSXpx
      aXZsNXFqWU1seEt2UGtlV3NIZld4TGQKNGNVQ0lBMi9aTXV4OVppM1ZwRVRYUURtM3FnTStYdFhv
      aTBYSTlvNStMYWU1RGFtCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KQg4KBFNIQTISBlNIQTI1
      NkrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWUxSndR
      ZnBJNFB6cEZhWG5sWmRIL0FvZzB2OHdDZ1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNS
      MEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURW
      UVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpN
      REV4TURNeE1ESXpNVGhhRncweU16QTRNalF4TURJek1UaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01R
      OHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNn
      d0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhr
      ak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVF3UjFJZXAwcDcrWFdqejRMZllZeGtHa2t1b1hvRURM
      Qzl6VWE2VUp3V0g2TW8rWVNycE80TVpxeDAxLzh4Cnovdy9NUWFqaXRTZUNCVm5MUzg4cXNsaG8w
      SXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhR
      NEVGZ1FVbC9XTk0zNXhXM1JMQzVpODhONWJHSzNXK0ZNd0NnWUlLb1pJemowRQpBd0lEU0FBd1JR
      SWhBUGI0bmxlVjc5MFMxTFhlT0c4QUhEMGtpbEoxcFd2dmRhUEhGcHZ6Z29xVUFpQW5PS2NuCjl4
      TDlkdEdRenEvdmIyZmpFV05RQnllb3NGY0dYcFBCT01Hbm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQpa7gsIARL0BQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlCK0RDQ0Fa
      NmdBd0lCQWdJVWUxSndRZnBJNFB6cEZhWG5sWmRIL0FvZzB2OHdDZ1lJS29aSXpqMEVBd0l3Cldq
      RUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5
      dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURWUVFEREE1allTNWpZWEp5YVdW
      eUxXNWxkREFlRncweQpNREV4TURNeE1ESXpNVGhhRncweU16QTRNalF4TURJek1UaGFNRm94Q3pB
      SkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhEekFOQmdOVkJBY01Ca3h2Ym1S
      dmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVBd3dPWTJFdVkyRnljbWxsY2kx
      dVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpBQVF3UjFJZXAwcDcrWFdqejRM
      ZllZeGtHa2t1b1hvRURMQzl6VWE2VUp3V0g2TW8rWVNycE80TVpxeDAxLzh4Cnovdy9NUWFqaXRT
      ZUNCVm5MUzg4cXNsaG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIKL3dR
      RUF3SUJwakFkQmdOVkhRNEVGZ1FVbC9XTk0zNXhXM1JMQzVpODhONWJHSzNXK0ZNd0NnWUlLb1pJ
      emowRQpBd0lEU0FBd1JRSWhBUGI0bmxlVjc5MFMxTFhlT0c4QUhEMGtpbEoxcFd2dmRhUEhGcHZ6
      Z29xVUFpQW5PS2NuCjl4TDlkdEdRenEvdmIyZmpFV05RQnllb3NGY0dYcFBCT01Hbm5nPT0KLS0t
      LS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBmNsaWVudBryBQrpBS0tLS0tQkVHSU4gQ0VSVElGSUNB
      VEUtLS0tLQpNSUlCK0RDQ0FaNmdBd0lCQWdJVWUxSndRZnBJNFB6cEZhWG5sWmRIL0FvZzB2OHdD
      Z1lJS29aSXpqMEVBd0l3CldqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZi
      akVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkRFlYSnlhV1Z5TVJjd0ZRWURW
      UVFEREE1allTNWpZWEp5YVdWeUxXNWxkREFlRncweQpNREV4TURNeE1ESXpNVGhhRncweU16QTRN
      alF4TURJek1UaGFNRm94Q3pBSkJnTlZCQVlUQWtkQ01ROHdEUVlEClZRUUlEQVpNYjI1a2IyNHhE
      ekFOQmdOVkJBY01Ca3h2Ym1SdmJqRVFNQTRHQTFVRUNnd0hRMkZ5Y21sbGNqRVgKTUJVR0ExVUVB
      d3dPWTJFdVkyRnljbWxsY2kxdVpYUXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CQndOQwpB
      QVF3UjFJZXAwcDcrWFdqejRMZllZeGtHa2t1b1hvRURMQzl6VWE2VUp3V0g2TW8rWVNycE80TVpx
      eDAxLzh4Cnovdy9NUWFqaXRTZUNCVm5MUzg4cXNsaG8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFR
      SC9NQTRHQTFVZER3RUIKL3dRRUF3SUJwakFkQmdOVkhRNEVGZ1FVbC9XTk0zNXhXM1JMQzVpODhO
      NWJHSzNXK0ZNd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBUGI0bmxlVjc5MFMxTFhlT0c4QUhE
      MGtpbEoxcFd2dmRhUEhGcHZ6Z29xVUFpQW5PS2NuCjl4TDlkdEdRenEvdmIyZmpFV05RQnllb3NG
      Y0dYcFBCT01Hbm5nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoSBHBlZXIaBkFkbWlucyIz
      CgdXcml0ZXJzEigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjQKBkFk
      bWlucxIqEiAIARIcEggSBggBEgIIABoQEg4KCmNhcnJpZXJNU1AQARoGQWRtaW5zIjcKC0VuZG9y
      c2VtZW50EigSHggBEhoSCBIGCAESAggAGg4SDAoKY2Fycmllck1TUBoGQWRtaW5zIjMKB1JlYWRl
      cnMSKBIeCAESGhIIEgYIARICCAAaDhIMCgpjYXJyaWVyTVNQGgZBZG1pbnMqBkFkbWlucxpAChVD
      aGFubmVsQ3JlYXRpb25Qb2xpY3kSJxIMCAMSCAoGQWRtaW5zGhcvQ2hhbm5lbC9PcmRlcmVyL0Fk
      bWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMiLQoGQWRtaW5zEiMSCAgBEgQSAhIAGhcvQ2hh
      bm5lbC9PcmRlcmVyL0FkbWlucyoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMaJgoQSGFzaGluZ0Fs
      Z29yaXRobRISEggKBlNIQTI1NhoGQWRtaW5zGi0KGUJsb2NrRGF0YUhhc2hpbmdTdHJ1Y3R1cmUS
      EBIGCP////8PGgZBZG1pbnMaYAoQT3JkZXJlckFkZHJlc3NlcxJMEjEKL29yZGVyZXIzLnN1cHBs
      eWNoYWluLW5ldC5zdmMuY2x1c3Rlci5sb2NhbDo4NDQzGhcvQ2hhbm5lbC9PcmRlcmVyL0FkbWlu
      cxomCgxDYXBhYmlsaXRpZXMSFhIMCgoKBlYxXzRfMxIAGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0I
      AxIJCgdSZWFkZXJzGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMi
      IgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMqBkFkbWlucxoOCgQKAgoACgAKAAoA
      CgA=
